### ISSUE TITLE
Rank issues

### ISSUE THREAD

**Issue by Attractor1one** [MobulaFi/mobula-feedbacks#101]
**Describe the bug**
When you view pages 1, 2, 3... 24, and come back, there is a violation in the rating. 
For example: 4 ranks No. 1

**To Reproduce**
1. Go to '(https://mobula.fi/?page=1)'
2. Go to '(https://mobula.fi/?page=24)'
3. Click on Rank
![2023-04-18_0](https://user-images.githubusercontent.com/126772418/232757273-c6d04ee1-7f5f-47b7-876d-b83d6a253678.png)
4. Go to back '(https://mobula.fi/?page=1)'
5. See error

**Expected behavior**
Restore the correct ranking.

**Screenshots**
![2023-04-18_1](https://user-images.githubusercontent.com/126772418/232755308-386dd07b-5605-475d-b3b3-1faf92394263.png)
![2023-04-18_2](https://user-images.githubusercontent.com/126772418/232755330-f4cbc59c-7d58-4fa0-a3f5-d10c0e7f5256.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [112.0.1]

**Comment by anouci** [comment]
Thank you for your feedback
