### ISSUE TITLE
Voting Issue/pending transaction 

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#102]
Its such a hustle to vote and get high fees. Its almost two hours and the transaction on Shangai vote is still pending. I tried changing the nonce but nothing happened. I hope to get a solution soon. 

This is the video after changing the nonce to my previous pending transaction. 

https://user-images.githubusercontent.com/101212685/232814221-73d05ecd-8362-4379-a08d-5d987f767ce9.mp4

**Comment by anouci** [comment]
Thank you for your feedback :) actually this bug is not from Mobula
