### ISSUE TITLE
Very high commission for the final vote

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#103]
**Describe the bug**
During the first voting for the listing of the token in the DAO, the commission is 0.05-0.07 MATIC with an average gas of 200 gwei at the moment. But during the final vote, the commission increases sharply to 0.5-0.6 MATIC

**To Reproduce**
1. Go to '[Protocol](https://mobula.fi/dao/protocol)'
2. Try to first vote and try final vote
3. See difference network fees

**Expected behavior**
Adjust final voting fee

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [112.0.5615.121]

**Comment by anouci** [comment]
Hey! The last person to vote will pay for the submission, and it's always a little more expensive than the rest, but there's not much we can do about it, sorry :)
