### ISSUE TITLE
there is an unusual volume increase bug in page gainer& loser , sort ETH

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#104]
![Screenshot_20230421-001351_Brave](https://user-images.githubusercontent.com/122985679/233440269-80a4c3f6-ddcb-4b6d-83b1-9c484182df62.jpg)
![Screenshot_20230421-001355_Brave](https://user-images.githubusercontent.com/122985679/233440289-8c3f5bb7-8167-422a-813d-ef9c9da4ea99.jpg)

**Comment by anouci** [comment]
Thank you!

**Comment by anouci** [comment]
Fixed
