### ISSUE TITLE
Editing telegram username on the website. By @victorgwatana

### ISSUE THREAD

**Issue by victorgwatana** [MobulaFi/mobula-feedbacks#105]
**Describe the bug**
When trying to edit the telegram username on the website the page just keep loading endlessly not allowing you to edit.

**To Reproduce**
1. Go to mobula.fi
2. Click on click on menu
3. Scroll down to profile and click on it.
4. Try to edit username.

**Expected behavior**
The page should allow editing of username.

**Screenshots**
If applicable, add screenshots to h
![Screenshot_20230422-103447](https://user-images.githubusercontent.com/72771715/233776811-ddfd5ca7-3220-4f25-98a8-49f47a1750d1.jpg)
elp explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Tecno spark 7p
 - Browser chrome

**Additional context**

**Comment by anouci** [comment]
Thank you for your feedback
