### ISSUE TITLE
Advanced search page.

### ISSUE THREAD

**Issue by victorgwatana** [MobulaFi/mobula-feedbacks#106]
**Describe the bug**
The advanced search page not working properly, on the page when I try to edit search settings the page freezes on its own, making it difficult to use.

**To Reproduce**
1. Go to the menu.
2. Click on tools.
3. Scroll down to advance search.
4. Try editing the search settings.

**Expected behavior**
The page should work smoothly, allowing users edit settings to get their search results.

**Screenshots**

**Desktop (please complete the following information):**
 - OS:

**Smartphone (please complete the following information):**
 - Device: Tecno spark 7p
![Screenshot_20230422-112042](https://user-images.githubusercontent.com/72771715/233779174-6d3166e5-21b6-4f26-a0ea-76df7d978ce4.jpg)

 - Browser chrome

**Additional context**

**Comment by anouci** [comment]
Hey :) I was not able to reproduce the bug. Can you please try again?

**Comment by victorgwatana** [comment]
Looks like it is working fine now, I just tried it now.

**Comment by anouci** [comment]
Cool
