### ISSUE TITLE
Mobula NFT not showing up

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#107]
**Describe the bug**
Mobula NFT are not displayed both in the profile and in the earn section. Although other NFTs are displayed correctly

**To Reproduce**
1. Go to '[Profile](https://mobula.fi/profile)' or '[Earn](https://mobula.fi/earn)'
2. See error

**Expected behavior**
Correct display of NFT

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/233875562-75c4146d-1707-49d8-bec6-766ca4c01dd5.png)
![image](https://user-images.githubusercontent.com/122439863/233875609-5ee4de3e-344a-4a68-b7b8-03dc9e152cc6.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [112.0.5615.138]

**Comment by anouci** [comment]
Thank you for the feedback
