### ISSUE TITLE
The price of tokens in the Portfolio section is not updated

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#108]
**Describe the bug**
The price of tokens in the Portfolio section is not updated. While in the watchlist section the price is displayed correctly

**To Reproduce**
1. Go to '[Portfolio](https://mobula.fi/portfolio)'
2. See incorrect token prices (MATIC or ETH for example)
3. Go to '[Watchlist](https://mobula.fi/watchlist)'
4. See correct tolen prices

**Expected behavior**
Correct prices of tokens

**Screenshots**
https://user-images.githubusercontent.com/122439863/233963979-6f3ac1be-a577-4709-bb59-027d8c1675f5.mp4

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [112.0.5615.138]

**Comment by anouci** [comment]
Thanks for the feedback

**Comment by anouci** [comment]
We will release an update for the portfolio with real-time market data
