### ISSUE TITLE
rugame listing 

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#109]
Its been 48hours since i voted on RUGAME listing on first sort, yet, so far, my vote has not been recorded by Mobulabot, its not on discord or telegram. what happened? 
could it be the reason it is still on rank 1? 
new listings in the last 24hours have already moved to rank 2 for final validation. 

regards.

**Comment by anouci** [comment]
Thanks. We are working on the problem with RUGAME

**Comment by anouci** [comment]
Problem with Chainstack, they are warned of the problem
