### ISSUE TITLE
Demote and promotions of Rank1 and Rank2 protocol DAO 

### ISSUE THREAD

**Issue by Godwinochebo** [MobulaFi/mobula-feedbacks#11]
All Rank 1 DAO who are not active should be romove and Rank 2 who did not vote for 5 days should be demote, while Rank1 who's active should be promoted to Rank2

**Comment by NBMSacha** [comment]
Hey! Thanks for this. This might be a Governance DAO proposal, not really the place for this - so I'm gonna close it :)
