### ISSUE TITLE
User name

### ISSUE THREAD

**Issue by Zeynabus** [MobulaFi/mobula-feedbacks#111]
When I want to change the username from the profile page, it seems to have changed first, but when we go to the main page and come back to the profile page, we see that the username is the same as before.

1. Go to profile page
2. Click on user name and change it and save
3. Again main page and go back profil page

 - Device: [Xiaomi note 10s]
 - OS: [Android 11RP1A.200720.011]
 - Browser [Tokenpocket app browser]
 - Version [1.7.2]

**Comment by anouci** [comment]
Can you please share a video?

**Comment by anouci** [comment]
Up
