### ISSUE TITLE
TG Command "/p (crypto)" buy button bug

### ISSUE THREAD

**Issue by ryuk998** [MobulaFi/mobula-feedbacks#112]
When u press the "Buy button" it goes to buy APE not to buy the crypto typed in the command.

**Comment by ryuk998** [comment]
https://user-images.githubusercontent.com/117784155/234580652-ad017272-2e7b-4c34-98c9-2d1835efeb1f.mp4

**Comment by anouci** [comment]
Thank you for the feedback, but next time, please respect the format when you report an issue :)
