### ISSUE TITLE
Error when switching wallets to view

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#113]
**Describe the bug**
Sometimes when you switching wallets for view, displayed the previous wallet information

**To Reproduce**
1. Go to '[Mobula](https://mobula.fi/)'
2. Click on 'Search'
3. Choose any wallet (Veeno for example)
4. Switch to Helpers wallet for example
5. See Veenos wallet displayed

**Expected behavior**
Correct switching between wallets

**Screenshots**
https://user-images.githubusercontent.com/122439863/234724774-ed115250-bee8-44d3-afdc-4d5571c7915c.mp4

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [112.0.5615.138]

**Comment by anouci** [comment]
Thanks for the feedback :)

**Comment by anouci** [comment]
Will be fixed in the next update
