### ISSUE TITLE
Ranking on Protocol DAO Stats

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#115]
Some mobulers' names appear twice on the stats ranking, that would be according to how many times mobulers have voted on listings. An example is attached below (see no. 48 and no. 49)

![Screenshot_20230427_182335_MetaMask.jpg](https://user-images.githubusercontent.com/101212685/234928434-f40ff6fc-ae50-4b1b-8b03-60064e534238.jpg)

**Comment by anouci** [comment]
Thanks :)

**Comment by anouci** [comment]
Fixed
