### ISSUE TITLE
Muted on TG for sharing Mobula help link

### ISSUE THREAD

**Issue by Nando-Lorris** [MobulaFi/mobula-feedbacks#116]
#**Describe the bug**
Got muted for sharing the link to the Mobula help group 
https://t.me/MobulaBotEcosystem
**To Reproduce**
1. Go to Mobula Telegram group
2. Paste link https://t.me/MobulaBotEcosystem
3. Receive 1 week mute x_x

**Expected behavior**
I expect to post link to the help group without receiving a ban
**Screenshots**
![Screenshot_20230429-040507_Telegram](https://user-images.githubusercontent.com/126595330/235294855-42fe721a-f797-4445-92bb-0af4a222b385.jpg)

**Smartphone (please complete the following information):**
 - Device: Android

**Additional context**

**Comment by anouci** [comment]
Thanks we will improve the filter system
