### ISSUE TITLE
Incorrect display in the mobile application

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#117]
**Describe the bug**
Daily streaks are displayed unevenly on the earn page

**To Reproduce**
1. Go to '[Earn](https://mobula.fi/earn)'
2. See incorrect display of text

**Expected behavior**
Align to display text for any display

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/235381467-58fd607b-4e5c-4b40-8724-092ff3fbdad5.png)

**Smartphone (please complete the following information):**
 - Device: [Galaxy ZFold 3]
 - OS: [Android 13]
 - Browser [Mobile app]

**Comment by anouci** [comment]
Thanks for the feedback

**Comment by anouci** [comment]
Fixed
