### ISSUE TITLE
Token chart not showing

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#118]
**Describe the bug**
Propy token chart is not displayed, which is specified in the daily mission 234

**To Reproduce**
1. Go to '[Earn page](https://mobula.fi/earn)'
2. Click on '234 Daily mission'
3. See error

**Expected behavior**
Correct display of token charts

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/235556024-c10ede57-743e-4492-919b-2a4da0a3a0c5.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [112.0.5615.138]

**Comment by anouci** [comment]
This is not a bug, the token is not yet launched.

**Comment by Midnight-yes** [comment]
> This is not a bug, the token is not yet launched.

Daily mission for unlaunched token?
And this token in Trendings
![image](https://user-images.githubusercontent.com/122439863/235617292-b9f03f10-775c-462a-ad16-412a5b14dd4d.png)
