### ISSUE TITLE
Twitter user name on profile page

### ISSUE THREAD

**Issue by Zeynabus** [MobulaFi/mobula-feedbacks#122]
When we enter our profile page, when we click to change our Twitter username, the page freezes as in the example image.

1. Go to the profile page
2. Click on Twitter username
3. Page is freezes

When we click on the Twitter username, we should be able to connect a new account or change the username

Smartphone 
 - Device: Xiaomi note 10s
 - OS: Android RP1A 200720.011
 - Browser : Tokenpocket app browser 
 - Version [1.7.3]

**
![Screenshot_2023-05-02-14-56-01-255_vip mytokenpocket](https://user-images.githubusercontent.com/131769019/235666581-f4c371d0-23af-45cf-a2e4-8471ba8ff913.jpg)

**Comment by anouci** [comment]
Hey can you please try again and let me know :)
