### ISSUE TITLE
Watch List

### ISSUE THREAD

**Issue by Zeynabus** [MobulaFi/mobula-feedbacks#124]
When I remove my watchlist and go to the page of the assets that were on my list before, I see that those assets are still on my watchlist.

1. Go to watchlist
2. Click delete icon
3. Go to one of assest page
4. Still see the star icon is yellow so still on watchlist
5. See error

When we delete the watchlist, we want the data about it to be deleted.

Smartphone

Device: Xiaomi note 10s
OS: Android RP1A 200720.011
Browser : Tokenpocket app browser
Version [1.7.3]

**Comment by anouci** [comment]
Hey! I can't reproduce the bug can you please share me a video
