### ISSUE TITLE
CEX trading volumes are not displayed for all tokens

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#125]
**Describe the bug**
Trading volumes on CEX are displayed for some cryptocurrencies (BTC, ETH, BNB for example). But for some reason, some tokens do not, although they are traded on many CEX (Pepe for example)

**To Reproduce**
1. Go to '[Pepe](https://mobula.fi/asset/pepe)'
3. See CEX Volume 0

**Expected behavior**
Correct display of trading volume

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/235821130-46943f06-0284-4ef0-b900-ac46dea2fef5.png)
![image](https://user-images.githubusercontent.com/122439863/235821173-f1af2363-ac43-4590-9050-deb23fd22b67.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [112.0.5615.139]

**Comment by anouci** [comment]
Will be fixed
