### ISSUE TITLE
Application error on Mobula DAO

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#126]
**Describe the bug**
Mobula protocol DAO is not connecting, error 

**To Reproduce**

**Expected behavior**
Overview, first sort, final validation, and stats

**Screenshots**
https://user-images.githubusercontent.com/101212685/235897158-cdcad76f-4cd3-413b-8129-e8bcbe42e9f8.mp4

**Smartphone (please complete the following information):**
 - Device: Samsung 
 - Android 13
 - Metamask (duckduckgo)

**Additional context**
I was unable to vote on the phone because of the issue. I had to switch to the desktop, which worked fine. Its been giving the error for about 5 hours now.

**Comment by anouci** [comment]
Fixed
