### ISSUE TITLE
Watchlist

### ISSUE THREAD

**Issue by Zeynabus** [MobulaFi/mobula-feedbacks#127]
When we add a new token to the watchlist, when we go to the watchlist and click on the three dots to the left of the token, the phrase "add to watchlist" appears.  When we click on the three dots to the left of a token that is already on our list, it says "remove from watchlist".  there is already an add again text for a newly added token in the list

1. Go to any token's page that is not on the watch list
2. Click on add watchlist
3. Go to your watchlist page
4. Click on the three dots to the left of the token you just added
5. see add to watchlist
6. When we do the same operation for the token that was previously in the watchlist, the phrase "remove watchlist" will be displayed instead of "add to watch list".
7. See error

All tokens in the expected status watchlist should have a remove clause

![Screenshot_2023-05-04-15-28-35-251_vip mytokenpocket](https://user-images.githubusercontent.com/131769019/236209108-1ca6763f-cd0f-4e79-8b02-89467fe1c446.jpg)
![Screenshot_2023-05-04-15-28-31-017_vip mytokenpocket](https://user-images.githubusercontent.com/131769019/236209124-8de9b9cd-9617-48c7-bc5a-86650e0dedb7.jpg)

Smartphone

Device: Xiaomi note 10s
OS: Android RP1A 200720.011
Browser : Tokenpocket app browser
Version [1.7.3]

**Comment by anouci** [comment]
Thanks for the feedback! Will we fix it
