### ISSUE TITLE
Error when claiming MATIC

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#128]
**Describe the bug**
When you try to claim a matic (for DAO voting) after the timer ends, the system gives an error

**To Reproduce**
1. Go to '[Protocol](https://mobula.fi/dao/protocol/overview)'
2. Click on 'Claim'
3. See error

**Expected behavior**
Commissions are now significantly higher when voting, need Matic

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/236581105-b123c7a7-d002-4581-8df4-aa2b013f893a.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [112.0.5615.138]

**Comment by anouci** [comment]
Can you please verify again?

**Comment by Midnight-yes** [comment]
> Can you please verify again?

https://user-images.githubusercontent.com/122439863/236793647-73c03757-2e49-44b8-b718-82d910ea42f3.mp4

Still not working
