### ISSUE TITLE
The web application does not display the total supply of tokens

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#129]
**Describe the bug**
The web application does not display the total supply of tokens. But in the mobile application, if click on the "metrics" then it displays

**To Reproduce**
1. Go to '[BTC for example](https://mobula.fi/asset/pro/bitcoin)'
2. See no total supply in metrics

**Expected behavior**
total supply is very useful information and I wanted it to be displayed in the web application too.

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/236596028-18106132-b7e7-4b73-9327-d1163decb2f8.png)
![image](https://user-images.githubusercontent.com/122439863/236596014-7d7314c4-5351-45ec-bdac-1444ec9e4239.png)

https://user-images.githubusercontent.com/122439863/236760342-aca80f98-2668-4d72-b6a2-d6c140ea6e0d.mp4

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [112.0.5615.138]

**Comment by anouci** [comment]
The problem will be fixed in the next update :)

**Comment by anouci** [comment]
Fixed
