### ISSUE TITLE
Trading schedule, swap possibility and other information of some tokens is not displayed

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#130]
**Describe the bug**
Some tokens that are listed on the mobula for some reason are not displayed (FLOKI for example)

**To Reproduce**
1. Go to '[Floki token](https://mobula.fi/asset/floki-inu)'
2. See no trading schedule and no swap option

**Expected behavior**
Correct display of all tokens that are listed on the mobula

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/236847087-7c277ac8-c08c-4033-b73d-1b6074d4b9b1.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [113.0.5672.64]

**Comment by NBMSacha** [comment]
Fixed! Thanks.
