### ISSUE TITLE
Portfolio displays incorrect balances

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#132]
**Describe the bug**
I noticed that some balances in the portfolio section are incorrect. For example, MATIC shows two times less than what I actually have

**To Reproduce**
1. Go to '[Portfolio](https://mobula.fi/portfolio)'
2. See incorrect balances

**Expected behavior**
Correct display of all assets

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/e0071a95-4e10-4622-8a06-61a12dddca58)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [113.0.5672.93]

**Comment by anouci** [comment]
It will be fixed with the new update :)
