### ISSUE TITLE
Advanced search 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#134]
**Describe the bug**
When you click on Share on the advanced search section you get an error 

**To Reproduce**
1. Go to TOOLS
2. Click on ADVANCED SEARCH 
3. Scroll down to SHARE
4. See error" APPLICATION ERROR"

**Expected behavior**
ONE SHOULD BE ABLE TO SHARE THEIR FINDINGS WHEN THEY TAP ON SHARE ICON

**Screenshots**
![IMG-20230515-WA0000.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/d06aa6a0-1f77-40aa-8781-ad697a927619)

**Desktop (please complete the following information):**
 - Windows 11
 - Browser [Brave]
 - Version [1.51.114]

**Smartphone (please complete the following information):**
 - Device: [e.g. SamsungA73]
 - Android: [13 ]
 - Browser [Brave]
 - Version [1.15.114]

**Additional context**

**Comment by anouci** [comment]
Thanks!

**Comment by anouci** [comment]
Fixed
