### ISSUE TITLE
Incorrect display of transactions in history

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#135]
**Describe the bug**
Some transactions in the history are shown twice, although in reality the transaction was sent once

**To Reproduce**
1. Go to '[Portfolio](https://mobula.fi/portfolio)'
2. See incorrect balance
3. Click on '[Mobula](https://mobula.fi/portfolio/mobula)'
4. See the last transaction shown twice
5. Go to '[Polygon scan](https://polygonscan.com/token/0x5fef39b578deeefa4485a7e5944c7691677d5dd4?a=0x01948a1dcc011b2b7de959d5c30c4b8fdfaa91ba)'
6. See one transaction

**Expected behavior**
Correct display of transaction history

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/51b8630c-d7d7-4ec9-8229-3ac32fa1ecd9)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/8e08a2d3-a4bc-4227-907f-b56ec32ea6e3)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/3d72fb1e-5ecf-4bfd-be6c-9fa5d6849f87)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [113.0.5672.93]

**Comment by anouci** [comment]
Hello, the new update will fix this issue

**Comment by Midnight-yes** [comment]
> Hello, the new update will fix this issue

Not fixed after update

**Comment by anouci** [comment]
Fixed
