### ISSUE TITLE
wrong price

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#14]
Sorry for this, sir, but some ALT coins also have inappropriate prices. one of them is flex coin. I don't know if this is a bug or not but I think it needs to be reported.
![20230119_144358](https://user-images.githubusercontent.com/122985679/213384566-aa55ef98-ddc2-4ca3-9e3d-dc17751dcc3b.jpg)
this from other chain
![Screenshot_20230119-144433_Brave](https://user-images.githubusercontent.com/122985679/213384613-97e13b9c-ce25-440f-a7db-709cfe0ebe98.jpg)
this from mobula

**Comment by NBMSacha** [comment]
Hey!

Thanks for this. However, price looks 100% matching on on-chain data (from DEXTools & Defined) - it looks that CoinGecko is wrong instead. 

Closing this :)
