### ISSUE TITLE
portfolio page loading time

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#140]
the portfolio page has been loading for more than 10mins without any changes, i tried to refresh a couple of times but 
 the response from the site was the same. 
https://mobula.fi/portfolio
![Screenshot (54)](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/75b22bf0-a18a-4f9c-928d-21221338ee61)

**Comment by anouci** [comment]
Thanks the team is working on it

**Comment by anouci** [comment]
Fixed
