### ISSUE TITLE
Not all NFTs are displayed correctly in the profile

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#143]
**Describe the bug**
Not all NFTs are displayed correctly in the profile

**To Reproduce**
1. Go to '[Profile](https://mobula.fi/profile)'
2. See error

**Expected behavior**
Correct display of NFT

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/4b64ea3a-7d8b-4d22-b656-3676a0d6757c)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [113.0.5672.127]

**Comment by anouci** [comment]
Thanks for the report!

**Comment by NBMSacha** [comment]
The thing is that this NFT never officially existed. That's why you can't fetch it.
