### ISSUE TITLE
So apparently on the option of one living comments on certain tokens was thinking it would be great if we could be in a position to view full comments and also be in a position to head back to the token information unfortunately here once it directs me to profile page of the person who wrote a comment i can't head back to the exact token but I'll have to start process again which takes long 

Kindly add Reply feature so that we can have a conversation with the person who commented on a specific token (sharing thoughts).

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#147]
![IMG-20230521-WA0004.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/72da34dc-d4e6-4bcf-941c-072f1454096f) here i can view the first comment but can't reply directly on the specific comment and also when i tap on the comment it takes me here 👇![IMG-20230521-WA0005.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/16083ac1-bfcb-4f5a-808b-5c33abd6f026)
Unfortunately i can't head back to the comment or even the selected token but have again to search afresh

**Comment by anouci** [comment]
Thanks for the feedback :) Next time please open a discussion
