### ISSUE TITLE
distinguishing tokens with similar tickers

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#15]
i searched for BFT token on mobulabot on telegram but got a different token from what i expected. 
currently we are using token tickers to check the prices on telegram.
checking on mobula website i found out there are more than one token with the ticker BFT.
i would like to know if there is a way we can distinguish the price of the token that we would like to see and not the mobula bot to assume that we want to see a certain token information. 

![Screenshot (6)](https://user-images.githubusercontent.com/101212685/213476975-ad74e799-2330-485b-928e-e9d12cfc259f.png)

**Comment by NBMSacha** [comment]
Hey!

You can use the name of your token in the /price command - this should do the trick.

Thanks.
