### ISSUE TITLE
Unable to get verification, on achievement and quest assignments, even though you have already made a transaction.

### ISSUE THREAD

**Issue by gusa51158** [MobulaFi/mobula-feedbacks#150]
**Describe the bug**
Unable to get verification, on achievement and quest assignments, even though you have already made a transaction. I just did the transaction as requested.

**To Reproduce**
1. Go to 'my profile...'
2. Click on 'achievements and quests then start quest....'
3. Scroll down to 'Mobula core features- The basics, 3 th add your first off- chain transaction..'

**Expected behavior**
Supposedly when we do a task, in this case is to make a transaction, when we have done the task, we can get verification as soon as it's completed.

**Screenshots**
This my tx hash. 0xe1d0e0c68693fb7cf9d5359edb098175c464d97aac36cf355e04d0f081ddb03b

**Desktop (please complete the following information):**
 -
 

**Smartphone (please complete the following information):**
 - Device: [e.g. infinix6816]
 - Version [e.g.kiwi browser 107.0.5304.74]

**Additional context**
-

**Comment by anouci** [comment]
Fixed
