### ISSUE TITLE
Hiding assets does not work correctly

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#153]
**Describe the bug**
Hiding assets not working after page refresh

**To Reproduce**
1. Go to '[Portfolio](https://mobula.fi/portfolio)'
2. Choose any asset and Click on 'Hide asset'
3. Refresh the page
4. See that asset unhided

**Expected behavior**
Ability to hide and unhide all assets correctly

**Screenshots**
https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/f4fc2047-dd48-49b2-9006-ab7ae2fc7a3c

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [113.0.5672.127]

**Comment by anouci** [comment]
Fixed with the next update

**Comment by anouci** [comment]
fixed
