### ISSUE TITLE
Portfolio 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#156]
**Describe the bug**
On the portfolio section when i remove/delete transactions of assets it shows me the exact previous Total amount i had not the current after removing them 

**To Reproduce**
1. Go to Portfolio 
2. Click on Assets
3. Scroll down to Asset to be deleted
4. Total value of previous asset still showing

**Expected behavior**
When one deletes/ removes a transaction of certain asset(s) the total value too should either not show or expect a decrease in value of total asset(s)

**Screenshots**
![IMG-20230524-WA0001.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/b0d09423-6691-4b76-9625-15321210f50c)

**Desktop (please complete the following information):**
 - OS [22621.1702]
 - Browser [Brave]
 - Version [1.51.118]

**Additional context**
NEED OPTIONS OF DELETE OR HIDE ASSET(S) not deleting entirely the whole asset transaction for privacy purposes

**Comment by anouci** [comment]
Hey Brian, on my side everything is working can you please make another test and let me know please
