### ISSUE TITLE
Contract address is not displayed for tokens

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#157]
**Describe the bug**
Many tokens do not display contract addresses. For example PEPE or even SHIBA

**To Reproduce**
1. Go to '[PEPE](https://mobula.fi/asset/pepe)' or '[SHIBA](https://mobula.fi/asset/shiba-inu)'
2. See only community info

**Expected behavior**
Correct display of contracts for tokens

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/1dafe6ae-910a-4533-8bb2-1785cb1c352c)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/d2062860-9441-4b7c-9cd2-4511e41b5c7b)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [113.0.5672.127]

**Additional context**
The error affects most tokens, but not all. For Bitcoin, for example, contracts are displayed
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/f71117c6-f584-424d-8cfe-1df28ad196b3)

**Comment by anouci** [comment]
Thanks for the feedback

**Comment by anouci** [comment]
fixed
