### ISSUE TITLE
network BNB not work. 

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#158]
**Describe the bug**
when changing the network to BNB, it takes a long time to load and when you select the selected coin when you want to swap or trade, does not respond.

**To Reproduce**
1. Go to ' change to BNB network
2. Click on ' trade selected coin  

**Expected behavior**

**Screenshots**

https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/8f3bed8d-36e3-4d10-a38f-83499f0ab34a

**Desktop (please complete the following information):**
 - OS: 10
 - Browser BRAVE browser
 

**Additional context**

**Comment by anouci** [comment]
fixed with wallet connect 2
