### ISSUE TITLE
Network switch 

### ISSUE THREAD

**Issue by Zeynabus** [MobulaFi/mobula-feedbacks#159]
I am trying to get a token from BNB network using dex.  But I cannot open and select other networks from the network selection section next to the earn icon above.  The page does not allow.

1. Go to dex page 
2. Click on network switch 
3. Scroll down to buy or sell ones

When we want to use the dex, we need to be able to select the network in order to be able to transact on the network included in the contract of the token we want to buy.

![Screenshot_2023-06-04-10-41-26-169_vip mytokenpocket](https://github.com/MobulaFi/mobula-feedbacks/assets/131769019/b5adce6a-a9e1-45ea-93aa-fc15d8d00b2b)

https://github.com/MobulaFi/mobula-feedbacks/assets/131769019/2cfa047e-d97c-4f3a-abd9-70b5e33ee6e8

Smartphone

Device: Xiaomi note 10s
OS: Android RP1A 200720.011
Browser : Tokenpocket app browser
Version [1.7.3]

**Comment by anouci** [comment]
Already reported
