### ISSUE TITLE
Mobula NFT

### ISSUE THREAD

**Issue by Zeynabus** [MobulaFi/mobula-feedbacks#160]
I cannot see my Mobula NFT when I go to my profile page even though I have completed all the tasks.  there is a closed screen

1. Go to profile page 
2.  Scroll down to where the NFT is

İ want to see my NFT

![Screenshot_2023-06-04-11-07-14-427_vip mytokenpocket](https://github.com/MobulaFi/mobula-feedbacks/assets/131769019/ec7dae75-3231-4710-9f4f-ed361ca48dfe)

Smartphone

Device: Xiaomi note 10s
OS: Android RP1A 200720.011
Browser : Tokenpocket app browser
Version [1.7.3]

**Comment by NBMSacha** [comment]
Hey! Thanks for reporting. It's sorted.
