### ISSUE TITLE
Twitter task in daily missions

### ISSUE THREAD

**Issue by Zeynabus** [MobulaFi/mobula-feedbacks#161]
When we click on the Twitter task defined in the daily tasks on the earn page, and open it with the Twitter application, when we return to the page, it shows the task as unfinished.  When you go to another page randomly and come back to the earn page, the task is completed.  but if we do it with the browser, not the application, there is no problem.

1. Go to earn page
2. Click on Twitter task
3. Open task to the Twitter app
4. And turn earn page
5. See error

When I return to the earn page from the Twitter application, I would like to see the task completed successfully.

Smartphone

Device: Xiaomi note 10s
OS: Android RP1A 200720.011
Browser : Tokenpocket app browser
Version [1.7.3]

**Comment by anouci** [comment]
Try to open it with your browser not the twitter app
