### ISSUE TITLE
Error while editing profile

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#164]
**Describe the bug**
Can't replace profile photo

**To Reproduce**
1. Go to '[My profile](https://mobula.fi/profile)'
2. Click on 'Edit profile'
3. Change profile pic
4. Click 'Save changes'
5. See error

**Expected behavior**
Ability to choose an avatar in the profile

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/4713c837-6fd9-4b11-ad7b-24b6403dff1a)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [114.0.5735.110]

**Comment by anouci** [comment]
Do you still have this problem?

**Comment by Midnight-yes** [comment]
> Do you still have this problem?

Fixed. Thanks)

**Comment by anouci** [comment]
Fixed
