### ISSUE TITLE
NFT is not displayed in the portfolio

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#165]
**Describe the bug**
NFTs are no longer displayed in the portfolio and profile. Yesterday they were displayed correctly

**To Reproduce**
1. Go to '[Portfolio](https://mobula.fi/portfolio)'
2. Click on 'NFTs'
3. See error

**Expected behavior**
Correct display of NFT in portfolio and profile

**Screenshots**
https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/822e4eb0-ebea-4a1c-bbd1-7c60a3c40571

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [114.0.5735.110 ]

**Comment by anouci** [comment]
Fixed
