### ISSUE TITLE
Mobula bot rewards

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#166]
On 14th june 2023, the bot did not reward all the 10 telegram mobulers who were active on the chat. 
Only 3 mobulers were rewarded a total of 13.75MOBL 
Here is a screenshot for confirmation 
![Screenshot_20230614_203844_Telegram.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/a0abd6b9-bb82-4641-8a0b-c8b5c64fa2f2)
Kindly check on it. 

Regards.

**Comment by anouci** [comment]
Thanks, we will send the rewards manually
