### ISSUE TITLE
NFT Minting

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#168]
I tried minting my NFT.
This is the response i got after completing the quest.

I used Trust wallet on iOS Ipad.

https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/47d52dab-b94b-4483-9051-cb4d98c53382

Kindly assist.

**Comment by anouci** [comment]
Thanks for the feedback :)

**Comment by anouci** [comment]
Please contact the support for this kind of problem :) Thanks
