### ISSUE TITLE
Matic faucet

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#171]
**Describe the bug**
Whenever i tap on matic faucet i get an error

**To Reproduce**
1. Go to Protocol dao
2. Click on Overview 
3. Scroll down to Faucet
4. Execution reverted

**Expected behavior**
Be in a position to claim matic

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser : Brave

**Comment by anouci** [comment]
Fixed
