### ISSUE TITLE
Mobula Trade

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#172]
**Describe the bug**
On mobula Trade after selecting the coin i want to buy and tap on the "Use card" option nothing is activated 

**To Reproduce**
1. Go to Trade
2. Click on step by step
3. Scroll down to Use card
4. Use card option not activated 

**Expected behavior**
I expect it to request for my card details

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Browser [Brave ]
 - Version [1.52.126]

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52.126]

**Additional context**
I really need to use this feature

**Comment by anouci** [comment]
Thank you for your feedback, the team is currently fixing it.

**Comment by anouci** [comment]
Fixed
