### ISSUE TITLE
Incorrect display of the token page

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#173]
**Describe the bug**
Some tokens (even from the top 50) are not displayed. For example the Stacks token

**To Reproduce**
1. Go to '[STX](https://mobula.fi/asset/stacks)'
2. See error

**Expected behavior**
Correct display of all tokens that are on the mobula

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/a5887f65-dfbc-4e65-bb9f-0bb5cc480435)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [114.0.5735.134 ]

**Comment by anouci** [comment]
Fixed
