### ISSUE TITLE
Token price on token(check time stamps one Screenshots)

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#174]
**Describe the bug**
When i check on BTC token price i.e 30,675 as of now and tap on the token to see price on chart there is a slight difference of 30664 and on portfolio page it indicates 30666

**To Reproduce**
1. Go to Asset page 
2. Click on BTC
3. Scroll down to BTC chart page
4. See error:  difference in price 

**Expected behavior**
Prices should be the same 

**Screenshots**
![Screenshot_20230624_171841_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/56e6c625-4554-4f60-8eb7-e1ebd5c89765)

![Screenshot_20230624_171831_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/6a2dd5bc-6348-4ed0-9ab9-c261bb03a704)

**Desktop (please complete the following information):**
 - windows 11
 - Browser : Brave
 

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [ Android 13]
 - Browser Brave
 - 

**Additional context**
Not only BTC but several tokens have the same issue

**Comment by anouci** [comment]
Fixed with the next update
