### ISSUE TITLE
network switch error

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#175]
https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/80232310-4c57-4549-93df-2fc79a82d5d8

trying to switch from polygon bnb smart chain network on mobula DEX but its not going through. 

1. Go to Tools
2. Click on Trade
3. Scroll to Chain then click to switch from polygon to bnb smart chain

 - Browser BRAVE

**Comment by anouci** [comment]
Fixed
