### ISSUE TITLE
Incomplete token information

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#176]
**Describe the bug**
Information about some tokens is incomplete. For example, a token that OriginTrail (TRAC) is in the 254 daily mission does not have trades available

**To Reproduce**
1. Go to '[OriginTrail](https://mobula.fi/asset/origintrail)'
2. See 'No trades available'

**Expected behavior**
Complete information about the token. Especially about those tokens that have daily missions

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/0a0b5138-955b-426a-9598-588ed39ee5d4)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [114.0.5735.134]

**Comment by anouci** [comment]
Fixed
