### ISSUE TITLE
Hide Asset on Portfolio 

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#177]
I wanted to delete the transactions for this said token (DKNIGHT) on my wallet 
but there was only one option.

Question: Do you want also delete your DKNIGHT transactions? 
Response: NO, JUST HIDE
Expectations: There is no option for YES, DELETE THE TRANSACTIONS. I suggest that it should be added. ![20230627_125750.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/549ed054-f2ce-45b1-9ffe-4ea2543c83a6)

Regards, 
Muhonja.

**Comment by anouci** [comment]
Hello :) we are aware of this issue

**Comment by anouci** [comment]
Will be fixed with the next update
