### ISSUE TITLE
Mobula Quest.

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#178]
Been on Mobula portfolio - Deep dive quest number 3.
It says 'sell abit of your crypto from your portfolio'
I did sell my matic to Tether but it has not reflected on the website for me to verify and continue with the quest.
Here is the harsh for confirmation
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/cd7e1772-5b19-4c1c-af3b-daf50cfbd850)
0x8962e641beecacb873c90db6b44fd8f956db54b7d9398ed794c95a7d1ff5b2ad HASH ID

**Comment by Mohdira** [comment]
Yes i did

**Comment by Mohdira** [comment]
Any help please?

**Comment by anouci** [comment]
Can you please record a video and do the whole process again, so I can understand where is the problem exactly. Thanks

**Comment by anouci** [comment]
Please don't confuse the issues. This one is dedicated to the quest, not the stake button. Did you ask the support?
