### ISSUE TITLE
error logout on Mobula web

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#179]
**Describe the bug**
can't log out... already refreshed 3x but still can't log out

**To Reproduce**
1. Go to '...' profile
2. Click on '....' log out

**Expected behavior**

**Screenshots**

https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/b00198cc-390f-4266-9f9d-80676b4f1b7f

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10
 - Browser Brave 

**Smartphone (please complete the following information):**

*

**Comment by anouci** [comment]
I can't reproduce the issue, I tried on the same device with Brave. What wallet are you using to connect?

**Comment by rian64** [comment]
now it's back to normal,.. before that it was very difficult to log out. like in the video

**Comment by anouci** [comment]
Ok thanks
