### ISSUE TITLE
Staking on Governance Dao

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#180]
I am trying to stake my MOBL tokens on Governance Dao but there is no staking button.
Or if it is there,its not working
Having used an Iphone XR.

https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/dd89efa3-e254-4570-a2dc-de23523b4b74

**Comment by anouci** [comment]
Very strange, what browser are you using?

**Comment by anouci** [comment]
The problem comes from Safari, thanks for the feedback

**Comment by anouci** [comment]
I'm using Brave too, but I can't reproduce the bug :/ can you send a video please

**Comment by anouci** [comment]
Fixed
