### ISSUE TITLE
Protocol Dao history

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#181]
**Describe the bug**
On the protocol Dao history page tokens that have passed First sort or Final validation keep reappearing several times which is unusual 

**To Reproduce**
1. Go to Dao
2. Click on Protocol Dao 
3. Scroll down to History section
4. Tokens reappearing 

**Expected behavior**
Once a token has passed either first sort or final validation it is supposed to show no of votes done and on the history page it has to appear once 

**Screenshots**
![Screenshot_20230628_225236_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/c98cc789-1a55-4fff-9219-db288e3a9a9f)

**Smartphone (please complete the following information):**
 - Device: SamsungA73 
 - OS: Android 13
 - Browser :Brave

**Comment by anouci** [comment]
Thanks for the feedback

**Comment by anouci** [comment]
Will be fixed with the next update
