### ISSUE TITLE
New icons not showing

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#182]
**Describe the bug**
New icons are not displayed on a mobile device. And from the computer in the browser are displayed correctly

**To Reproduce**
1. Go to '[Mobula](https://mobula.fi/)'
2. Click on 'Cryptocurrencies or Tools or Ecosystem or Mobula DAOs'
3. See error

**Expected behavior**
Correct display of icons

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/ef8b1a4a-af76-4875-8695-f4274e197b2d)

**Smartphone (please complete the following information):**
 - Device: [Samsung Galaxy Z3]
 - OS: [Android 13]
 - Browser [Chrome or mobile app]

**Comment by anouci** [comment]
Thanks for the report :)

**Comment by anouci** [comment]
Fixed
