### ISSUE TITLE
Buying using Credit card 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#183]
**Describe the bug**
After requesting for my BNB wallet address and tap continue it tells me something went wrong

**To Reproduce**
1. Go to Tools
2. Click on Swap
3. Scroll down to Buy step by step
4. Use card and find error messages 

**Expected behavior**
Not so sure what should be the next step since am using the tool today 

**Screenshots**
![IMG-20230629-WA0009.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/25cb96ff-1c5b-440b-8e6a-de72a95cc73e)

.

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [Brave]
 - Version [1.52.136

**Additional context**
Guidelines on who to go about it please.

**Comment by anouci** [comment]
You need to use a BNB Beacon Chain address

**Comment by BrianArunga** [comment]
Exactly what am using as you can see on the screenshot

**Comment by anouci** [comment]
Did you try with a BEP20 instead BEP2?

**Comment by BrianArunga** [comment]
BEP-20

**Comment by BrianArunga** [comment]
![Screenshot_20230629_175559_Trust Wallet.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/b09f1026-e9a0-4097-8786-a647df89ae07)

Is there a place we have to fill in our card details?

**Comment by anouci** [comment]
Did you try with a BEP2?

**Comment by BrianArunga** [comment]
Yes i did (bnb1erep6ua80sgl9jwwx67ry5vj8zylyuapp55qwp)

**Comment by anouci** [comment]
Ok we will investigate on our side, but it's a bug from the payment solution

**Comment by BrianArunga** [comment]
Thanks

**Comment by anouci** [comment]
The whole process will be upgraded
