### ISSUE TITLE
Quest

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#184]
**Describe the bug**
Start Quest icon has disappeared 

**To Reproduce**
1. Go to profile page
2. Click on My profile
3. Scroll down to Achievements &Quests
4. Start Quest missing 

**Expected behavior**
Start Quest should always be available no matter the no: of times you refresh page

**Screenshots**
![Screenshot_20230629_190416_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/beb631a4-48f2-479f-8d7b-f1e121ea2103)

.

**Desktop (please complete the following information):**
 - OS: [Wimdows 11]
 - Browser Brave
 - Version [1.52]

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Comment by anouci** [comment]
The "start a quest" button is only displayed when the user has not made any quest and, therefore no badge.

**Comment by BrianArunga** [comment]
Immediately i was done with the 5 usdc transaction the icon disappeared that means i can't proceed with quest😫
