### ISSUE TITLE
NFTs not showing up on profile

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#185]
**Describe the bug**
After the update, the NFT was no longer displayed in the profile. Cleared cookies and reconnected the wallet - did not help

**To Reproduce**
1. Go to '[Profile](https://mobula.fi/profile)'
2. See error

**Expected behavior**
Correct display of all NFTs

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/84b75636-cdff-4750-bea0-1fb5cb50247f)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [114.0.5735.134 ]

**Comment by anouci** [comment]
Thanks for the report :)

**Comment by anouci** [comment]
Is the bug still here?

**Comment by anouci** [comment]
Fixed
