### ISSUE TITLE
Wallet explorer via Search icon

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#186]
**Describe the bug**
Let's say i want to check on veeno's portfolio using the search option since i don't have his wallet address,i will use search option and type his name and i get directed to his portfolio but right now am being directed on their profile page 

**To Reproduce**
1. Go to Mobula page
2. Click on Search icon
3. Scroll down to Type Veeno
4. You get directed to profile page not portfolio 

**Expected behavior**
Normally we  use Search icon to check on portfolio unless there are changes now.

Screenshot 
![Screenshot_20230630_174617_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/bcad3e9b-07b5-4232-a4d5-1ab90229e1b3)

 -->![Screenshot_20230630_174601_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/a820f313-815c-4792-ab21-3a3f388b9844)

…

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52.]

**Comment by NBMSacha** [comment]
This is a feature, not an issue - we think that if you search by username, you're doing a social search = profile. Elseway, it's a wallet search = explorer.
