### ISSUE TITLE
 the number of portfolio coins does not match those in wallets, such as Matic and Mobula . in the Mobula transaction data there are 2x the same transaction

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#187]
**Describe the bug**

**To Reproduce**
1. Go to '...'portfolio

**Expected behavior**

**Screenshots**

![Screenshot_20230630-215238_Brave](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/2059e701-28fe-481a-bd3c-9a3186310b08)

![20230630_220238](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/3c1a5b4c-2473-4b2a-8322-2a6f61167e38)

this is from bitkeep wallet data
![20230630_220536](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/6017afa4-d909-4ee9-86a0-983994708505)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 10
 - Browser [e.g. chrome, safari] brave

**Smartphone (please complete the following information):**

**Additional context**

**Comment by anouci** [comment]
Thank you, already reported :)
