### ISSUE TITLE
Voting buttons not working

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#190]
**Describe the bug**
Unable to click validate or reject on a vote

**To Reproduce**
1. Go to '[Protocol](https://mobula.fi/dao/protocol/sort)'
2. Click on 'Validate or Reject'
3. See error

**Expected behavior**
Correct ability to vote

**Screenshots**
https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/fe73b59e-377f-4097-88de-c25abb6d3d40

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [114.0.5735.134]

**Comment by anouci** [comment]
Thanks, the team is working on it. :)

**Comment by anouci** [comment]
Fixed
