### ISSUE TITLE
Contracts are not displayed for some tokens

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#191]
**Describe the bug**
Contracts for some tokens are not displayed (for example Akash Network). At the same time, for example, for bitcoin, all addresses of contracts are displayed correctly

**To Reproduce**
1. Go to '[AKT](https://mobula.fi/asset/akash-network)'
2. See no contract address

**Expected behavior**
Correct display of contracts for all tokens

**Screenshots**
https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/d2de6475-08c6-490f-8a4e-18738b4aeffe

**Desktop (please complete the following information):**
- OS: [Windows]
- Browser [Chrome]
- Version [114.0.5735.134]

**Comment by anouci** [comment]
Thanks for the report

**Comment by anouci** [comment]
This one can't be fixed for now (AKG)
