### ISSUE TITLE
double claim

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#192]
**Describe the bug**
The last time the claim was enabled, some users pressed the claim, but the system sent the tokens twice

**To Reproduce**
1. Go to '[This wallet for example](https://polygonscan.com/token/0x5fef39b578deeefa4485a7e5944c7691677d5dd4?a=0x1f1fe0c2c9ae8d0c22ab944f06af9a9b24d23980)'
2. See Double receipt of tokens in large quantities

**Expected behavior**
Correction of the token redemption system. Now that user has 421 extra tokens. And there can be many such addresses.

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/bbe19600-cdf2-4cba-8af3-c33f0f6acf3a)

**Desktop (please complete the following information):**
Does not matter

**Comment by Midnight-yes** [comment]
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/e58949f9-ed95-4345-8bed-1ac397b64ade)
https://polygonscan.com/token/0x5fef39b578deeefa4485a7e5944c7691677d5dd4?a=0xd293781a69311869aabe8dcb358361dd26f4220f
Another similar double transaction 2 days ago. In this case, it is not at all clear how the user could make a claim, since the claim is disabled.

**Comment by Midnight-yes** [comment]
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/40331453-c196-4299-9595-546b50eb546d)

https://polygonscan.com/token/0x5fef39b578deeefa4485a7e5944c7691677d5dd4?a=0x32dd79d03a2a9eb019f5db9b8ba9db0359f4ff03
Another similar double transaction right now!

**Comment by anouci** [comment]
Fixed
