### ISSUE TITLE
Daily missions reward system for new joiners

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#193]
**Describe the bug**
When a newbie joins and claims mobl for the first time on Daily streaks they should get 1 mobl in their on-chain app but seems we have a bug when taps 1 mobl they get 10 mobls in turn 

**To Reproduce**
1. Go to Earn and learn
2. Click on Daily streaks 
3. Scroll down to "mobula owes you"
4. Excess tokens given

**Expected behavior**
The required amount of mobl to be distributed as it is on the Daily streak section

**Screenshots**
![IMG-20230706-WA0034.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/fd0d6404-4f48-4d19-922e-091779791c6a)

**Comment by BrianArunga** [comment]
Hope to this into consideration?

**Comment by NBMSacha** [comment]
Hey! 10 MOBL are given when the user comes from referral - it's part of the referral program.
