### ISSUE TITLE
Pulsechain Application Error

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#195]
**Describe the bug**
On Recently added token when you check on Pulsechain you find an Error 

**To Reproduce**
1. Go to Cryptocurrency 
2. Click on Recently Added
3. Scroll down to Pulsechain 
4. See error: "APPLICATION ERROR"

**Expected behavior**
It should open and be able to see all token details

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Browser Brave
 - Version 1.52

**Smartphone (please complete the following information):**
 - Device: SamsungA73 
 - OS: Android 13
 - Browser [Brave]
 - Version 1.52

**Additional context**
Apparently Github has an issue,can't share screenshot

**Comment by anouci** [comment]
Fixed
