### ISSUE TITLE
Incorrect balance of MOBL tokens in the portfolio

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#196]
**Describe the bug**
In the portfolio, the number of some tokens is displayed incorrectly (for example, MOBL)

**To Reproduce**
1. Go to '[Portfolio](https://mobula.fi/portfolio)'
2. Click on 'Show low balances'
3. See Incorrect number of MOBL tokens

**Expected behavior**
Correct display of all assets in the portfolio

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/7746e668-2fd9-4c38-be37-f7c49e5e3134)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/c4732f38-506f-48f6-8945-f33f185cbbee)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [114.0.5735.134]

**Comment by anouci** [comment]
The portfolio is being completely updated, it will be fixed
