### ISSUE TITLE
Contract Address on Current Listing 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#198]
**Describe the bug**
On Protocol Dao the current listing we can't access the C/A

**To Reproduce**
1. Go to Protocol Dao 
2. Click on First sort 
3. Scroll down to New list
4. Contract address icon not active 

**Expected behavior**
When we tap on Contract address icon it should redirect us to chain explorer to verify details of token.
**Screenshots**
![Screenshot_20230710_223006_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/fff0aa3b-6974-4e6b-a05b-b8288418e573)

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**

**Comment by anouci** [comment]
Thanks for the report!

**Comment by anouci** [comment]
Fixed
