### ISSUE TITLE
Mobula bot unresponsive 

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#199]
The bot has gone mute for a couple of hours on Mobula Telegram thus inconveniencing users. Kindly check on it. 

Refer to the screenshot below. 
![Screenshot_20230711_070557_Telegram.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/e1c36cad-2a9c-4775-995b-d826ba848b1c)

**Comment by anouci** [comment]
Thanks for report!

**Comment by anouci** [comment]
Fixed
