### ISSUE TITLE
Metamask has been stuck for sometimes

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#201]
Having tried to log into my Mobula wallet but unable!

Says server with the host name can't be found.

Below is an image of what i got as response in support of the bug report.

[image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/8dd5243d-39d7-4a5c-bc18-67c2bc3e78b7)

**Comment by anouci** [comment]
Can you please try directly from mobula.fi/profile

**Comment by anouci** [comment]
Let me know if you still have this error

**Comment by Mohdira** [comment]
Am good now.
Thanks
