### ISSUE TITLE
Croc website 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#202]
**Describe the bug**
Website of the new listing isn't responding 

**To Reproduce**
1. Go to Protocol Dao
2. Click on First sort 
3. Scroll down to Croc token
4. See error: Website not loading 

**Expected behavior**
When clicking on the website it should load and get access to token website 

**Screenshots**
![Screenshot_20230711_145820_Brave.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/ff1c4349-71cb-40f6-b910-1cbdf7e6a382)

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**

**Comment by anouci** [comment]
It's not on our side :) I tried and after 5 minutes the site responded

**Comment by BrianArunga** [comment]
Let me keep trying 

Thanks
