### ISSUE TITLE
Incorrect token price

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#203]
**Describe the bug**
The price of some tokens is displayed incorrectly (for example, MATIC)

**To Reproduce**
1. Go to '[MATIC](https://mobula.fi/asset/polygon)'
2. See incorrect token price

**Expected behavior**
Correct prices for tokens. I have to check with other crypto aggregators, it's not very good

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/3557c67b-ec37-4552-af35-d591ce009e7c)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/f5f80a70-0d1e-4b1f-9547-fb2bb24efaf8)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/c5093c94-601b-4d19-b8d5-c04d77cbcc9d)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [114.0.5735.199]

**Comment by anouci** [comment]
Fixed, thanks for the report
