### ISSUE TITLE
New listing contract address not responding 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#204]
**Describe the bug**
Th3 current new listing contract address link is unresponsive 

**To Reproduce**
1. Go to Protocol Dao 
2. Click on First sort 
3. Scroll down to New listing 
4. See error(contract not responding)

**Expected behavior**
When tapping on the contract address link it should respond and direct us to contract explorer 

**Screenshots**
![Screenshot_20230712_121523_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/6bdd5618-51f8-4f2b-a5b7-6c12881c3faa)

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13 ]
 - Browser [Brave]
 - Version [1.52]

**Additional context**

**Comment by anouci** [comment]
Thanks for the feedback

**Comment by anouci** [comment]
Fixed with the next update
