### ISSUE TITLE
Contract address on the Erica Social projectnot working

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#205]
The immediate new listing's contract now responding.
The contract has an error in opening therefore unable to explore more in it.

Attached is a screenshot to accompany my complain.

Report being sent from Iphone XR
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/6aeda46b-0e7d-45ba-b987-c727b23a8158)

**Comment by anouci** [comment]
Thanks already reported
