### ISSUE TITLE
Social Ranking in Protocol Dao new listing 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#206]
Team,since we have 3 main social networks being used by most Crypto communities it would be wise if we have them all on Social ranking i.e Telegram,Discord and Twitter, why am i suggesting so it's because when voting for new listings on social section scores we only have options for Twitter and telegram and not discord so when having to vote for listing that only have Discord as their preferred social network we remain stranded on what score to provide .

**Comment by anouci** [comment]
Interesting, can you share it in the discussions tab please
