### ISSUE TITLE
Profile page 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#208]
**Describe the bug**
When i open profile page section i get an error 

**To Reproduce**
1. Go to Mobula features section 
2. Click on profile page
3."Internal server error

**Expected behavior**
Should direct me to profile page 

**Screenshots**
![Screenshot_20230714_173511_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/5331e6c9-7526-4e88-9fae-5c9422d0485c)

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**

**Comment by anouci** [comment]
Fixed
