### ISSUE TITLE
on the page profile, portfolio and mobula NFT do not appear

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#210]
**Describe the bug**

**To Reproduce**
1. Go to '...' profile 

**Expected behavior**

**Screenshots**
![20230715_194119](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/d848740b-db9e-4a02-8af1-1d4f497cfbab)
.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. android 10
 - Browser  brave
 - Version 

**Additional context**

**Comment by rian64** [comment]
all fixed

**Comment by anouci** [comment]
Thanks
