### ISSUE TITLE
When more than one contract address the system associate them with wrong blockchain

### ISSUE THREAD

**Issue by TheHelperalive** [MobulaFi/mobula-feedbacks#211]
**Describe the bug**
System messing up the contract addresses and blockchain when projects filled up the form and send it for voting. 

**To Reproduce**
During the vote if a project has more than 1 contract with new blockchains click on any and it will fill contract address from different blockchain and shows that contract doesn't exist or some not relevant address

**Expected behavior**
System automatically detect the correct blockchain that contract related 

**Screenshots**
Not related

**Desktop (please complete the following information):**
Not related

**Smartphone (please complete the following information):**
Not related

**Additional context**
Not related

**Comment by NBMSacha** [comment]
Hey! Thanks for reporting. This is being sorted by the new release next week.
