### ISSUE TITLE
Protocol DAO stats 

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#213]
The total number of RANK I and RANK II Protocol DAO members stands at 76 but the list showing the names and total number of votes per person stands at 59. Where are the missing 17 Mobulers? One of the member also noticed that his name was not appearing on the list yet he is an active member. 
Kindly refer to the screenshots below. 

![Screenshot_20230717_060012_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/9bb30224-47ff-496f-892d-82f9d6fbe1e3)

![Screenshot_20230717_060030_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/8e909fe6-b9c3-4141-80ee-ff82ea16d13e)

![Screenshot_20230717_060613_Telegram.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/7b2405ad-7b2a-4fea-b75d-f431c1d8ccbf)

**Comment by anouci** [comment]
It's a not a bug :) it's just because the 17 didn't vote
