### ISSUE TITLE
MOBULA LOGO

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#215]
**Describe the bug**
Since the update of white mode on mobula app the colour of the Logo and "Mobula" changed too,i think we they have to retain there colour also on phone it acts kinda sluggish when you tap on light mode icon

**To Reproduce**
1. Go to mobula app
2. Click on light mode

**Expected behavior**
When changing modes Mobula logo should retain its colour and light mode icon should be fast not sluggish 

**Screenshots**
![Screenshot_20230717_093320_Brave.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/3fe60590-a726-42fc-b577-169c8f840ea7)

![Screenshot_20230717_093253_Brave.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/2c8be108-306d-4023-8749-6fd78f2ae439)

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - Ios: Android 13
 - BrowotherBrave ]
 - Version [1.52]

**Additional context**

**Comment by anouci** [comment]
Thanks for the feedback
