### ISSUE TITLE
Essentials Icon Unresponsive 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#217]
**Describe the bug**
When you tap on any given token and check on the Essentials icon it doesn't respond
**To Reproduce**
1. Go to Mobula page 
2. Click on Any token
3. Scroll down to Essentials
4. See error (Unresponsive)

**Expected behavior**
I literally don't know the purpose of Essential icon but would be great to find out once up and running 

**Screenshots**
![IMG-20230717-WA0001.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/540c8ada-66ac-459c-b1ec-1cac21a2809b)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Brave]
 - Version [1.52]

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**
Would like to know its purpose if it's not ready then include 🚫 on the cursor

**Comment by anouci** [comment]
Thanks for the feedback

**Comment by anouci** [comment]
It's not a bug, we will add in the next update content for this section
