### ISSUE TITLE
Landwolf Token Bug on Recently Added 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#219]
**Describe the bug**
When you open the Recently added tokens and click on "Landwolf Token the page redirects you back to main page 

**To Reproduce**
1. Go to Recently Added tokens
2. Click on Landwolf Token
3. Token page doesn't load

**Expected behavior**
Should open page where we get full details of the token

**Screenshots**
![Screenshot_20230719_084853_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/c89a9f73-13fb-45e1-9106-919bd062846e)

![Screenshot_20230719_085457_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/266d9b7d-22f6-4f7a-8143-ea2d30946b55)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Brave]
 - Version [1.52]

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Comment by anouci** [comment]
Thanks

**Comment by anouci** [comment]
Fixed
