### ISSUE TITLE
Search for tokens does not work correctly

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#220]
**Describe the bug**
When trying to search for a token, for example, Arkham, if you enter the first 3 characters of 'Ark' in the search string, then this token cannot be found, you need to enter an additional character. Although other tokens that start with 'Ark' are searched correctly.

**To Reproduce**
1. Go to '[Mobula](https://mobula.fi/)'
2. Click on 'Search'
3. Enter 'Ark'
4. See some tokens but not Arkham

**Expected behavior**
Correct search for all tokens, since the user, having entered several characters and not finding the desired token, may think that this token is not on Mobula

**Screenshots**
https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/6e2c1e61-32eb-4dc0-a6d7-f4b2e391752f

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [114.0.5735.199 ]

**Comment by anouci** [comment]
Thanks for the feedback

**Comment by anouci** [comment]
It's not a bug. The search is limited to six suggestions.
<img width="430" alt="Screenshot 2023-07-21 at 13 55 00" src="https://github.com/MobulaFi/mobula-feedbacks/assets/48858984/43c68e3b-e6e1-45da-8741-65e380567540">

**Comment by Midnight-yes** [comment]
> limited to six suggestions.

limited to five suggestions =)
Maybe in this case, the rest of the tokens with the same beginning of the name can be in the drop-down list?
