### ISSUE TITLE
Swap not working

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#224]
**Describe the bug**
When trying to swap, the system gives an error

**To Reproduce**
1. Go to '[Trade](https://mobula.fi/trade)'
2. Try to swap (AIDI token for example)

**Expected behavior**
Fast swap without errors

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/4b10681d-faf0-4aa5-ac30-0626f9bbe52a)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/de8dcb1f-f007-4b91-beae-8892f607d449)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [115.0.5790.99]

**Comment by anouci** [comment]
On my side, I can't trade AIDI on Polygon. Is it AIDI inu or AIDI Finance?

**Comment by Midnight-yes** [comment]
> On my side, I can't trade AIDI on Polygon. Is it AIDI inu or AIDI Finance?

Previously, I calmly bought this token on the mobula. at the address of the contract. I just inserted the contract address and bought. Their contract has been updated a long time ago, but the old contract is on mobula

**Comment by anouci** [comment]
Can you send the ca please

**Comment by Midnight-yes** [comment]
0xdfc2c4ce66561c3ee53dbea9ff78550f395a25e2

**Comment by Midnight-yes** [comment]
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/71760c9e-d3f0-4b5f-9eeb-0f436c5367d6)
And it is also impossible to make a swap if the slipage token has more than 0.5%, only through the trade section

**Comment by NBMSacha** [comment]
Hey! Thanks, this has been identified. Issue is that we don't take price change due to swap into the default output amount, this is going to be sorted next week. Thanks!
