### ISSUE TITLE
New listing appearing on Recently Added 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#225]
**Describe the bug**
Token details don't appear despite the fact token itself has already been listed and can be seen on Recently Added section

**To Reproduce**
1. Go to Mobula homepage 
2. Click on Cryptocurrencies
3. Scroll down to Recently Added 
4. See error Unibot token is visible but token details not available 

**Expected behavior**
Once listed token and its details should be visible 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**
Issue has been consistent on most of the Recently added tokens

**Comment by anouci** [comment]
Their trust score is low that's why
