### ISSUE TITLE
Portfolio 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#228]
**Describe the bug**
When i check my Total Investment on portfolio it gives me unrealistic figure 

**To Reproduce**
1. Go to Homepage 
2. Click on Portfolio 
3. Scroll down to Total Invested
4. See error 12,687$😳

**Expected behavior**
Should show the exact total amount invested 

**Screenshots**
![Screenshot_20230722_094928_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/6f16be51-a527-4c04-ab39-db90986a12ae)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Brave]
 - Version [1.52]

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Comment by anouci** [comment]
Is this error still here?

**Comment by BrianArunga** [comment]
Nope,all good now
