### ISSUE TITLE
Network change not working

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#229]
**Describe the bug**
Nothing happens when I try to change the network

**To Reproduce**
1. Go to '[Mobula](https://mobula.fi/)'
2. Click on 'Network'
3. Try change another

**Expected behavior**
Correct change of networks

**Screenshots**
https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/a035bfb2-fc8c-4d51-9bb6-7b5583857360

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [115.0.5790.99]

**Comment by NBMSacha** [comment]
Fixed!! Thanks.
