### ISSUE TITLE
Profile page showing an error

### ISSUE THREAD

**Issue by dCodeX21** [MobulaFi/mobula-feedbacks#230]
**Describe the bug**
When trying to do the genesis quest "2/5. Link your Telegram account", upon clicking the url to redirect to profile page, an "Application error: a client-side exception has occurred".

**To Reproduce**
1. Go to '[Mobula Genesis Quest](https://mobula.fi/earn)'
2. Scroll down to 'Quest Section'
3. Click on 'profile page'

**Expected behavior**
Should redirect to a profile page which is briefly showing before the error occurs.

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/104153652/d268fa04-9d59-40cc-895b-fd0bdb0841f3)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Brave]
 - Version [1.56.11 Chromium: 115.0.5790.102 (Official Build) (64-bit)]

**Comment by anouci** [comment]
Hey :) Do you still need help with this problem?
