### ISSUE TITLE
Notification setting on mobula website

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#231]
Under **Learn&Earn** it reads:
You’ll be notified when a new Learn&Earn _campain_ is out.
I believe the word should be _campaign_

Under **New Listings** it reads: 
You’ll be notified when you’re about to lose your streaks
Basically, there are no streaks involved when there is a new listing that is to be voted for by members of Protocol DAO on Mobula. The description should be changed. 

Refer to the screenshot attached. 
![bandicam 2023-07-23 16-20-34-935](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/99ff0bae-e2fa-4f9a-a968-0a18ae014ef6)

**Comment by anouci** [comment]
Thanks for the feedback

**Comment by NBMSacha** [comment]
Fixed thanks!!
