### ISSUE TITLE
DAO VOTE PROTOCOL open links in the same tab

### ISSUE THREAD

**Issue by TheHelperalive** [MobulaFi/mobula-feedbacks#232]
**Describe the bug**
When a project listed for a vote a dao member checks links provided. When click on one of the links in any section "Contract', "Community", "Audit" etc. it opens in the same windows. That requires to go back to voting page and start again. 

**To Reproduce**
Go to (https://mobula.fi/dao/protocol/sort) open a project, click on links 

**Expected behavior**
As before, when click on a link it opens in a new tab, not the same. 

**Screenshots**

**Desktop (please complete the following information):**
 Windows
 
**Smartphone (please complete the following information):**

**Additional context**

**Comment by anouci** [comment]
Fixed

**Comment by TheHelperalive** [comment]
Nope, the same for me :)
