### ISSUE TITLE
Duplicate Information 

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#233]
There are 2 listings for _Coin-coin_ each on First Sort and Final Validation instead of one each since DAO votings are always done once. 

1. Go to _**Protocol DAO overview**_
2. Scroll down to **_History_**
3. See error

The final tally should be 2, one for First Sort and another for Final Validation. 

 - Samsung M12
 - Browser Metamask dapp
 - Version 6.3.0

Screenshot for reference. 

![Screenshot_20230725_050434_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/f6cf611e-953f-4d21-90fb-8a3abff21cd0)

**Comment by NBMSacha** [comment]
Hey! Thanks a lot. This will be sorted by the release of the protocol upgrade.
