### ISSUE TITLE
Problem on daily mission 

### ISSUE THREAD

**Issue by Nando-Lorris** [MobulaFi/mobula-feedbacks#234]
**Describe the bug**
Mission says to follow Sacha on Twitter but I already follow him lol I still logged in on the dapp browser, made no difference 

**To Reproduce**
1. Go to earn tab
2. Click on Daily mission (Follow Sascha on Twitter)
3. Scroll down to 

**Expected behavior**
Completed daily mission 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]Android 
 - Browser [e.g. stock browser, safari]Trust Wallet 

**Additional context**

**Comment by NBMSacha** [comment]
Hey! Thanks a lot, this is a growth hack to make sure people do follow me!! 😁 not a bug.
