### ISSUE TITLE
Incorrect display of zeros for tokens

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#239]
**Describe the bug**
If the price of the token has a large number of zeros after the decimal point, then the user does not understand what the price of the token is. If you hover over the price, then "e-7" is displayed

**To Reproduce**
1. Go to '[Lovely inu](https://mobula.fi/asset/lovely-inu-finance)'
2. Hover over price
3. Incomprehensible price

**Expected behavior**
Clear price for the user with a total number of zeros

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/cc266689-698c-4f2f-ad1a-e23f19cab28b)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [115.0.5790.102]

**Comment by NBMSacha** [comment]
Thanks! This is sorted.
