### ISSUE TITLE
HOW TO..LINKS HAVE ERRORS

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#241]
**Describe the bug**
Most of the support links shared on telegram page don't function but produce erros making it hard for members to report issues 

**To Reproduce**
1. Go to Mobula telegram page
2. Click on .howto
3. Scroll down to Support links generated
4. See internal server error 504 on most links

**Expected behavior**
When selecting a link it should direct you to the page one needs to access without any issues 

**Screenshots**
I![Screenshot_20230729_154146_Telegram.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/f4eb08e6-b38b-4158-a6a7-70701cc888d3)

**Smartphone (please complete the following information):**
 - Device: SamsungA73
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Comment by ChristianOGB** [comment]
Thanks Brian. This will be sorted.

**Comment by BrianArunga** [comment]
To make it easy check on the following:

*Fast Track listing*
*7 ways to earn *
*Use the Earning system *
*Dex or trade features *
*Mobula convert* 
*Governance proposal*
*Open support ticket and lastly Report bugs on Github*

All the above links are producing errors![Screenshot_20230801_115326_Brave.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/bc0b8c29-ec53-405c-a5b6-8282531d7bc8)
