### ISSUE TITLE
Price of WLD token not accurate 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#242]
**Describe the bug**
Price on Etherscan and price on Mobula App are totally different 

**To Reproduce**
1. Go to Wld token
2. Click on Contract address 
3. Scroll down to Price indicated on both etherscan and mobula App
4. See error Price are different 

**Expected behavior**
Since Mobula collects its data from Blockchain i do expect the price on both ends tally

**Screenshots**
![Screenshot_20230729_173528_Brave.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/7b477589-95ff-4770-9f5b-f5ea2bf780d6)

![Screenshot_20230729_173404_Brave.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/5681ba04-8250-4607-95df-e6f8d7dfc51e)

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**

**Comment by anouci** [comment]
Fixed
