### ISSUE TITLE
Token has an old contract

### ISSUE THREAD

**Issue by Attractor1one** [MobulaFi/mobula-feedbacks#244]
**Describe the bug**
Token Gala (GALA) has an old contracts + wrong price is also indicated (Screenshot 1).
Using outdated contracts can be dangerous when trading.
Information about the new smart contract is posted on the official website of the project (https://games.gala.com/get-gala) (Screenshot 2).

**To Reproduce**
1. Go to '[GALA](https://mobula.fi/asset/gala)'
2. Click on the Contracts button
3. Click on '[1st old contract](https://etherscan.io/token/0x15d4c048f83bd7e37d49ea4c83a07267ec4203da)' + Screenshot 3
4. Click on '[2nd old contract](https://bscscan.com/token/0x7ddee176f665cd201f93eede625770e2fd911990)' + Screenshot 4
5. See error
6. Now look at the new smart contract '[new contract](https://etherscan.io/token/0xd1d2Eb1B1e90B638588728b4130137D262C87cae)'
7. Look at the new price '[GALA on Uniswap](https://app.uniswap.org/#/swap?inputCurrency=ETH&outputCurrency=0xd1d2eb1b1e90b638588728b4130137d262c87cae)'

**Expected behavior**
Update smart contract and fix price.

**Screenshots**
1 
![изображение](https://github.com/MobulaFi/mobula-feedbacks/assets/126772418/3b846757-1b88-410d-ba42-f3588fb7e15b)
2 
![изображение](https://github.com/MobulaFi/mobula-feedbacks/assets/126772418/ad36378c-02dc-4240-8e47-4456d22d6b3d)
3 
![изображение](https://github.com/MobulaFi/mobula-feedbacks/assets/126772418/5c370c5c-8f5b-48f7-98f3-7a6bb43ab56d)
4 
![изображение](https://github.com/MobulaFi/mobula-feedbacks/assets/126772418/0f8fe569-5ab2-43d8-8d6b-60ad1e25e336)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [115.0.3esr]

**Comment by anouci** [comment]
Thank you, fixed!
