### ISSUE TITLE
NFT is no longer displayed in Portfolio

### ISSUE THREAD

**Issue by Attractor1one** [MobulaFi/mobula-feedbacks#246]
**Describe the bug**
NFTs is no longer displayed in "Portfolio". But in "My Profile" everything all right, NFTs is displayed. 

**To Reproduce**
1. Go to '[Portfolio](https://mobula.fi/portfolio)'
2. Click on "NFTs" button
3. See error

**Expected behavior**
The portfolio displays NFTs.

**Screenshots**
![изображение](https://github.com/MobulaFi/mobula-feedbacks/assets/126772418/4f7d60ed-e90c-43b1-88b5-8b3d42846427).

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [115.0.3esr]

**Comment by anouci** [comment]
Hello :) Do you still have this problem? Can you share me the wallet you are trying to access (DM)?

**Comment by Attractor1one** [comment]
Hello ) Yes, sure: 0x365b5fb610cf246c82e3a49f220aa4b7134cfdea

**Comment by anouci** [comment]
Fixed
<img width="985" alt="Screenshot 2023-08-25 at 10 56 16" src="https://github.com/MobulaFi/mobula-feedbacks/assets/48858984/726c9d02-f199-41ca-9945-c3f39948ab31">
