### ISSUE TITLE
Problem with chart range

### ISSUE THREAD

**Issue by Nando-Lorris** [MobulaFi/mobula-feedbacks#249]
**Describe the bug**
Went to the Gate Token chart. I prefer candle bars and noticed I could select a different range (24h, 7d, 1yr etc) and nothing changes but works fine on the default setting. Screenshots below

**To Reproduce**
1. Go to Gate Token
2. Click on "candle bars"
3. Scroll down to change to 24hr, 7d, 1yr etc

**Expected behavior**
Chart range to change to desired timeframe

**Screenshots**
![Screenshot_20230801-133520_Trust Wallet](https://github.com/MobulaFi/mobula-feedbacks/assets/126595330/aaa8258f-a1c5-4f55-8945-1a3f242052b9)
![Screenshot_20230801-133535_Trust Wallet](https://github.com/MobulaFi/mobula-feedbacks/assets/126595330/0106554b-36dd-4125-852b-42362255d046)
![Screenshot_20230801-133654_Trust Wallet](https://github.com/MobulaFi/mobula-feedbacks/assets/126595330/bb5145d9-46fa-42a6-a63d-e6230ea41838)
![Screenshot_20230801-133706_Trust Wallet](https://github.com/MobulaFi/mobula-feedbacks/assets/126595330/ab7c48e9-d529-4d91-a477-32baeb52b1ff)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]Android 
 - Browser [e.g. stock browser, safari]Default 

**Additional context**

**Comment by anouci** [comment]
Thanks for the feedback :) The time range that you are using is the one dedicated to the "default" view. We will hidde it each time that you are using the trading view to avoid any confusion.
