### ISSUE TITLE
Lists of tokens in the trend are different

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#252]
**Describe the bug**
The lists of tokens in the trend on the main page and in the full list are different

**To Reproduce**
1. Go to '[Main page](https://mobula.fi/)'
2. We will see 3 tokens in the trend section
3. Click on '[More](https://mobula.fi/trendings)'
4. We will see other tokens in the trend

**Expected behavior**
Same display of tokens in a trend

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/c53df73a-a2b6-47cf-b14c-af651ea4e3e2)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/279072b0-9d70-4d71-b58a-9227b6dde347)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [115.0.5790.110]

**Comment by anouci** [comment]
Fixed: the complete ranking is updated in real time, sometimes a little ahead of the preview on the home page.
