### ISSUE TITLE
Some token no price display

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#255]
**Describe the bug**
Some tokens no price display, vol. and some information about social media such as Twitter is also unreadable, but after being traced it to their Twitter. this happens to some of the listed tokens.

**To Reproduce**

**Screenshots**

https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/d1cbb15f-fb08-49bd-a313-acb200335497

![20230807_200752](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/e728bf2d-db31-4d88-a32d-4566a4d647e6)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Android 10
 - OS: [e.g. iOS8
 - Browser Brave

**Comment by anouci** [comment]
Fixed: It takes some time for data to be aggregated, and some projects are just not launched yet
