### ISSUE TITLE
Listing not opening

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#260]
Upon clicking on the new project to be listed,the website isn't opening.
Thus an application error!

[image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/8653cdaa-2ce9-47fb-ac06-2b95e9d0c9af)
Attached is a screenshot stating an error.
Report from Iphone XR

**Comment by anouci** [comment]
Fixed
