### ISSUE TITLE
Error when trying to vote YEBAT

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#261]
**Describe the bug**
Error when trying to vote YEBAT

**To Reproduce**
1. Go to '[YEBAT](https://mobula.fi/dao/protocol/sort/yebat)'
2. See error

**Expected behavior**
Correct display

**Screenshots**
https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/e4a4295a-7e2d-4002-9d56-4b6fa862d35d

**Comment by Midnight-yes** [comment]
Trend Guru - the same situation
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/58ba92d0-b301-42a5-9726-80231c7ad36a)

**Comment by anouci** [comment]
Fixed
