### ISSUE TITLE
french connection finance (FCF )token, after finishing in the first vote it doesn't appear to the final vote, and immediately token listing.

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#263]
![Screenshot_20230807-223454_Telegram](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/e923915d-02b0-45d9-b16c-779609f814bf)
![Screenshot_20230807-222225_Brave](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/66af7fe4-ddec-421e-a858-a780c3efedb1)

**Comment by anouci** [comment]
Fixed
