### ISSUE TITLE
french connection finance (FCF )token bug

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#264]
French connection finance (FCF)token has been voted by rank 1 and rank 2 protocol DAO members but none of the voting appear on HISTORY under OVERVIEW tab on Mobula Protocol. Normally every listing shows the number of votes that appear on first sort and on final validation.  

**To Reproduce**
1. Go to PROTOCOL 
2. Scroll down to OVERVIEW
3. Check on HISTORY

![bandicam 2023-08-07 18-59-05-585](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/ef7e7859-6faf-46e7-8bf6-97e3df46c352)

**Comment by anouci** [comment]
Fixed
