### ISSUE TITLE
French Connection Finance (FCF) token info display

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#265]
French Connection Finance (FCF) token details are not being displayed on mobula website. the token has been listed since the name can be searched and it appears but when you click on it, it tries to load the page but an error occurs. 
Brave browser. 

https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/ffb382cd-4cef-40c5-bfb2-d3ae97993a45

**Comment by anouci** [comment]
Fixed
