### ISSUE TITLE
 Trend Guru (TRENDGURU) voting bug

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#266]
Trend Guru (TRENDGURU) is a new listing on mobula that needs to be voted on protocol DAO but on clicking the tab it gives an error. video for reference. 

https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/4eada33b-a8ed-41b8-9740-38961b4a71c6

**Comment by Midnight-yes** [comment]
After reconnecting the wallet, the voting page started working

**Comment by anouci** [comment]
Fixed
