### ISSUE TITLE
no sorting for ARB chain in page trending and Recently added

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#267]
#**Describe the bug**
In the top 100 of the page, there is the ARB chain. but in the recently added and trending page it doesn't exist. On the other hand, those FTM chain are not included in the Top 100 page

**To Reproduce**
1. Go to ' Page Top 100 rank Mobula you can find sorting ARB chain there .
2. Click on you Page recently added and trending, Chain ARB it's not there

**Screenshots**
![20230808_012743](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/a072e0c8-f1da-498a-af9b-5822d170b6fe)
![20230808_012709](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/3e76fde4-7088-4d02-9ca6-cae09dbcc527)

**Comment by anouci** [comment]
Fixed
