### ISSUE TITLE
Sythetix network token

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#271]
**Describe the bug**
When you search for Synthetix Network Token you get an Application error

**To Reproduce**
1. Go to Mobula 
2. Click on Search Bar
3. Scroll down to Synthetix Network token
4. See error Application Error

**Expected behavior**
Normally once you search a token on the search bar it should open and give you all details about the token

**Screenshots**
![Screenshot_20230808_081458_Brave.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/bc325ad2-243d-4ae6-9f9a-a0f5439111bc)

.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Brave]
 - Version [1.52]

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**

**Comment by anouci** [comment]
Fixed
