### ISSUE TITLE
error for when trying to click token listing

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#273]
![Screenshot_20230808-213809_Brave](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/136a9803-96da-436e-9207-0c977d7605aa)

https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/18d965e2-541c-420b-9d4c-46f0df9c7cc3

**Comment by anouci** [comment]
Fixed
