### ISSUE TITLE
Unable to vote on the new listing on pest Educational solutions

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#274]
The project is listed but on clicking on it to open so as to analyse deeper information about it,an error occurs and can't open below is ascreenshot attached to show the Error
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/63143a69-646b-47d6-b278-17222b5f5a6e)
Report from Iphone Xr

**Comment by anouci** [comment]
Fixed
