### ISSUE TITLE
Unable to open the new project listed.

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#275]
The paypal USD also does not open on clicking to check on the inner details in it.
Attached are screenshots to show the Application ![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/bc597f0e-9e02-4c6a-9136-4eb991ad137e)error![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/d0ebfe38-d53c-45a1-93ff-30ed1169e287)
Reported bug from Iphone XR

**Comment by anouci** [comment]
Fixed
