### ISSUE TITLE
TrendGuru on Recently Added 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#279]
**Describe the bug**
When you tap on Trendguru token on Recently Added tokens you get application Error 

**To Reproduce**
1. Go to Mobula
2. Click on Recently Added 
3. Scroll down to TrendGuru token
4. See error "APPLICATION ERROR 

**Expected behavior**
Once you select a token it should open directly and get token details 

**Screenshots**
![Screenshot_20230808_192355_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/be98f644-1c6c-4555-8a45-041bc5a0fa5f)

.

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**

**Comment by anouci** [comment]
Fixed
