### ISSUE TITLE
some Token not showing their Dex Volume 24h.

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#281]
https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/be6efcf3-6eca-43e9-8341-fcc2b1156ad4

![Screenshot_20230808-235829_Brave](https://github.com/MobulaFi/mobula-feedbacks/assets/122985679/805459cb-cb57-487e-8b09-22e6969bda04)

**Smartphone (please complete the following information):**
 - Device: android 10
 - OS: 
 - Browser Brave browser

**Additional context**

**Comment by anouci** [comment]
Already reported
