### ISSUE TITLE
DAO protocol page error

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#284]
**Describe the bug**
An error occurs when trying to login to the DAO protocol page

**To Reproduce**
1. Go to '[Protocol](https://mobula.fi/dao/protocol)'
2. See error

**Expected behavior**
Correct page display

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/52b00643-e8ac-4eaf-8fe2-7e3bb49364f3)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [115]

**Comment by NBMSacha** [comment]
On it, will be sorted within 1h, thanks.
