### ISSUE TITLE
No contract address on the new SHIGOKu listing

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#287]
The contract address does not appear when clicking on the listed project.
Also when trying to vote and submitting it shoes an error.
Below is a screenshot and a clip to show the error.

![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/594f9004-861b-48d1-8e4d-17aed2380765)https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/d117fdeb-cdb2-4aae-a59a-d29c8ca9ddfe

Bug reported from Iphone XR

**Comment by anouci** [comment]
Fixed
