### ISSUE TITLE
Incorrect redirect

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#288]
**Describe the bug**
When trying to go to any token from the listing history, an incorrect redirect occurs

**To Reproduce**
1. Go to '[Protocol overview](https://mobula.fi/dao/protocol/overview)'
2. Click on 'any token from history'
3. See redirect to non-existent page

**Expected behavior**
Correct work of the entire section

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/4936b523-e8de-4094-94ca-69ef3cfc31fc)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/23358b94-ff2d-4f01-ac2a-b03c4e7f9a05)
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/87ccebef-1684-4c42-8808-8545c44d4caa)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [115]

**Comment by anouci** [comment]
Fixed
