### ISSUE TITLE
MOBULA PORTFOLIO 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#289]
**Describe the bug**
When i head to Portfolio page ,asset section and tap on an asset i get Application error

**To Reproduce**
1. Go to Mobula 
2. Click on Portfolio 
3. Scroll down to Asset page
4. See error Application Error 

**Expected behavior**
I should be in a position to see transactions i made on specific Assets 

Screenshots 

https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/652bc198-ced9-4827-82cb-0d13c591b208

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**

**Comment by anouci** [comment]
Fixed
