### ISSUE TITLE
Portfolio page not loading

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#292]
**Describe the bug**
Portfolio page not loading, waiting more than 2 minutes

**To Reproduce**
1. Go to '[Portfolio](https://mobula.fi/portfolio)'
2. See error

**Expected behavior**
Portfolio fast loading

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/08de0344-2ffe-4a12-a685-5cf78a7a67c4)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [115]

**Comment by Midnight-yes** [comment]
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/57a164a4-5406-44ff-a2d2-e3bed69653cc)
Also, token charts and trading history are not loaded.

**Comment by anouci** [comment]
Fixed
