### ISSUE TITLE
Showcasing of listing rewards on Protocol DAO

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#293]
**Describe the bug**
Once a project would be listed,it would show rewards to offer.
And after both Ranks would vote and validated,the rewards would be Keyed in not soo long and a member would claim them.
Since the last votings and validations,it still shows nothing was rewarded

**To Reproduce**
1. Go to '...'Mobula DAOS
2. Click on '....'Protocol
3. See error

**Expected behavior**
Having had claimed my last rewards and left 0 claim,I would expect from the last validated listings to have rewards reading on claim.

![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/09384aec-8d63-4012-bb77-663aff98d5ac)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone XR]

**Comment by anouci** [comment]
Thanks for the feedback

**Comment by anouci** [comment]
It seems that it was already reported
