### ISSUE TITLE
Listing sent on Telegram but not appearing on DAOS for voting

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#294]
**Describe the bug**
New listing on Telegram but not on MOBULA DAO for voting

**To Reproduce**
1. Go to '...'MOBULA DAOS
2. Click on '....'Protocol
3. Scroll down to '....'First sort

**Expected behavior**
A clear indication that once its already sent to Telegram,it should be ready on protocol DAO for first sort

**Screenshots**
https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/f36e7721-bcfd-414f-b1b2-24fae36dbc2d![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/86f36440-7bbe-4aab-8f35-0222ee7a04a1)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone XR]
 - 

**Additional context**
Am not sure if its for Admins vote or DAO members.

**Comment by NBMSacha** [comment]
Not a bug, listing is in the pending pool because didn't pay enough.
