### ISSUE TITLE
Voting history.

### ISSUE THREAD

**Issue by victorgwatana** [MobulaFi/mobula-feedbacks#298]
**Describe the bug**
On the voting page when you click on any of the voting history, it displace an error page.

**To Reproduce**
1. Go to the menu
2. Click on mobula DAOs then protocol.
3. Scroll down to voting history 
4. Click on any token in the history 

**Expected behavior**
It is supposed to display the token details normally.

**Screenshots**

**Desktop (please complete the following information):**
 - 
 - Browse
 - Vers

**Smartphone (please complete the following information):**
 - Device: [teckno spark 7p]
 - Browser [chrome
![Screenshot_20230818-071319](https://github.com/MobulaFi/mobula-feedbacks/assets/72771715/fa1e8384-c33f-4e31-bd95-7a6e9f880ef7)
]

**Additional context**

**Comment by anouci** [comment]
Thank for the report!

**Comment by anouci** [comment]
Already reported
