### ISSUE TITLE
Page view is not available

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#30]
**Describe the bug**
Switching pages 2,3,4 and so on does not work. When you try to go to any page, the very first one opens again

**To Reproduce**
1. Go to 'https://mobula.fi/'
2. Scroll down to 'page numbers'
3. Click on any page

**Expected behavior**
Correct display of all tokens on all pages is required

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/220250402-714d8aac-54a4-4d45-ae0f-a0914b5186a4.png)
![image](https://user-images.githubusercontent.com/122439863/220250468-ab34dd22-ca1c-4726-bbf8-ba6cc3edb715.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 110.0.5481.97

**Comment by anouci** [comment]
Fixed! Thanks :)
