### ISSUE TITLE
Matic faucet 

### ISSUE THREAD

**Issue by victorgwatana** [MobulaFi/mobula-feedbacks#300]
**Describe the bug**
The matic faucet for dao members is not working, it displays an error that says something went wrong, this error message started coming up when the contract was changed.

**To Reproduce**
1. Go to menu (mobula DAOs)
2. Click on protocol 
3. Scroll down to the faucet 
4. See error, click on claim

**Expected behavior**
When you click on claim, the faucet is supposed to give one matic weekly.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [teckno spark 7p]
 - Browser [chrome
![Screenshot_20230818-071352](https://github.com/MobulaFi/mobula-feedbacks/assets/72771715/6da9b731-bc87-4e9f-88bf-756ae4322e4e)
]

**Additional context**

**Comment by anouci** [comment]
Thanks for the report

**Comment by anouci** [comment]
Already reported
