### ISSUE TITLE
Global community gone missing on Discord.

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#303]
**Describe the bug**
Apparently,global section on discord just went missing.

**To Reproduce**
1. Go to Discord
2. Click on International chat
3. Scroll down to communities

**Expected behavior**
When you click on International chat,global should appear first before any other international community.

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/afbb1852-082c-4fbf-b6e8-7980e711f2e8)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneXR
 -

**Additional context**
In conviniencing members airing their views or chats in English.

**Comment by anouci** [comment]
Take a look in the community section. You will find general-chat :)
