### ISSUE TITLE
BondAppetiteUSD

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#304]
**Describe the bug**
Token has taken 1st position against BTC

**To Reproduce**
1. Go to Mobula homepage 
2. Click on Top 100
3. Scroll down to Position 1
4. See error USDAP

**Expected behavior**
1st coin has to be BTC

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Comment by anouci** [comment]
Thank you! The team is aware of this problem and we are fixing it :)
