### ISSUE TITLE
Disconnected wallet.

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#306]
**Describe the bug**
After having received rewards on my daily activity on a daily basis,today it shows no wallet no rewards.

**To Reproduce**
1. Go to Discord
2. Click on general chat
3. Scroll down to processing rewards for activity leaderboard

**Expected behavior**
I expected to be rewarded but it read No wallet no reward yet its the same wallet i have been being rewarded on

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/dc999542-8869-467c-91d2-2b3fa511beec)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhoneXR]
 

**Additional context**
At what point does someone wake up to a no wallet yet it has been working all through since i set it.
I would like to know why the wallet was disconnected.

**Comment by anouci** [comment]
Thanks for the report! Did you change your username?

**Comment by Mohdira** [comment]
No. I did not

**Comment by anouci** [comment]
Ok! Contact Christian maybe he can send you some rewards depending on the situation

**Comment by Mohdira** [comment]
Ok thanks
