### ISSUE TITLE
The trade section does not load from PC

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#310]
**Describe the bug**
The trade section does not load from PC. But it work from smartphone

**To Reproduce**
1. Go to '[Trade](https://mobula.fi/trade)'
2. See error

**Expected behavior**
Partition performance from any device

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/cc378278-cfc9-49e8-a471-2fe87eda0a02)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [116]

**Comment by anouci** [comment]
Fixed
