### ISSUE TITLE
Telegram showing but opening on Twitter

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#312]
**Describe the bug**
On community,the third community indicates Telegram but on clicking it,it takes one back to Twitter

**To Reproduce**
1. Go to protocol Dao
2. Click on first sort
3. Scroll down to community

**Expected behavior**
I expect it to open on Telegram and not send me back to twitter since the third community indicates Telegram
**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/514a27c5-3013-4d0a-a2cf-aef9bf5939ac)

 

**Smartphone (please complete the following information):**
 - Device: [Iphone XR.

**Comment by anouci** [comment]
Thanks for the feedback. We will fix it rapidly
