### ISSUE TITLE
Error on XRP swap

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#315]
**Describe the bug**
When you click on a token all the details should appear including the swap details. after loading the page a couple of times the swap details do not appear as shown below. 

**To Reproduce**
1. Go to XRP token page
2. See error

**Expected behavior**
the names of the tokens for swapping to appear. 

https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/2f8ea9ba-3c69-4203-bafb-63ee607a631b

**Desktop (please complete the following information):**
 -Brave Browser

**Comment by NBMSacha** [comment]
Hello! This is sorted, can you please check back and confirm?
