### ISSUE TITLE
New listing Dawae on search bar 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#317]
**Describe the bug**
When you go to search bar and type Dawae the newly listed token it appears twice 

**To Reproduce**
1. Go to Mobula Homepage 
2. Click on  Search bar
3. Scroll down to  Dawae token

**Expected behavior**
It should only appear once

**Screenshots**
![Screenshot_20230903_203000_MetaMask.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/edf8c8ac-15d4-4497-ace3-1ef87f139dea)

**Smartphone (please complete the following information):**
 - Device: [SamsungA73]
 - OS: [Android 13]
 - Browser [Brave]
 - Version [1.52]

**Additional context**

**Comment by NBMSacha** [comment]
Not the same token.
