### ISSUE TITLE
Trade volume not displayed

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#319]
**Describe the bug**
Some tokens do not display trading volume (Boost for example)

**To Reproduce**
1. Go to '[Boost token page](https://mobula.fi/asset/boost)'
2. See Volume 0

**Expected behavior**
Correct display of information for all tokens that are on Mobula

**Screenshots**
![image](https://github.com/MobulaFi/mobula-feedbacks/assets/122439863/4917e856-6161-4f99-b870-f55c0a98d30b)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [116]

**Comment by anouci** [comment]
Thanks for the report
