### ISSUE TITLE
Unable to chat on fun page on Discord

### ISSUE THREAD

**Issue by Mohdira** [MobulaFi/mobula-feedbacks#321]
**Describe the bug**
When i get to fun page on Discord and click to write a message,it skips back to general.
Meaning i can't participate on Fun page

**To Reproduce**
1. Go to Dicord
2. Click on Fun 

**Expected behavior**
I expect to be able to write ok fun page without it skipping and taking me back to General chat.
 
Screen shots yo show the error
![Uploading 266800832...]https://github.com/MobulaFi/mobula-feedbacks/assets/136676391/b1814842-3efc-46cd-8028-dfac104a4f88

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone XR
 

**Additional context**
I would like to chat on fun page independently.

**Comment by anouci** [comment]
Fixed :)
