### ISSUE TITLE
Portfolio Error

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#326]
**Describe the bug**
Portfolio page gives error when clicked from the homepage.

**To Reproduce**
1. Go to Homepage
2. Click on Portfolio
3. See error

**Expected behavior**
My portfolio with my assets and balances. 

**Screenshots**
![bandicam 2023-09-14 13-00-25-920](https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/24da54ef-c039-490b-b789-d0fbd86a12c9)

https://github.com/MobulaFi/mobula-feedbacks/assets/101212685/f4f3e8a2-c397-46f2-9d8b-98c7c7140c79

**Desktop (please complete the following information):**
 - Browser Brave
 - Version 1.57.64

**Comment by anouci** [comment]
Fixed
