### ISSUE TITLE
Advanced Search

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#327]
**Describe the bug**
Since the new update of the Homepage we can not access the advanced search option which was a useful tool to use

**To Reproduce**
1. Go to Mobula homepage 
2. Click on Tools
3. Scroll down to 

**Expected behavior**
When opening the Tools section it should appear there which it's not the case now

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Brave]
 - Version [1.52]

**Additional context**
BRING IT BACK PLEASE

**Comment by anouci** [comment]
Ok thanks for the feedback
