### ISSUE TITLE
ATOM and DOGE supply error

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#33]
![Screenshot_20230226-082629_Brave](https://user-images.githubusercontent.com/122985679/221387890-ea67d0d9-b807-42a8-8a0a-d651ea973715.jpg)
![Screenshot_20230226-084544_Brave](https://user-images.githubusercontent.com/122985679/221387895-b8796681-4636-4d0c-9d3e-dd4abdc7fbd5.jpg)
token ATOM dan DOGE menunjukan supplay 0 di web

**Comment by ChristianOGB** [comment]
Hi @rian64 ,
It's better to write in English and add your Telegram and Discord ID.

**Comment by ChristianOGB** [comment]
+ the title could be more precise, like "suppply error" 😉
