### ISSUE TITLE
Connect MobulaFi using Safari browser 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#331]
**Describe the bug**
When connecting to MobulaFi using Safari browser i got an Error which opted me to use brave browser as default browser 

**Expected behavior**
When searching and connecting MobulaFi on any browsers we should be able to connect without any errors 

**Screenshots**
![IMG-20230917-WA0000.jpg](https://github.com/MobulaFi/mobula-feedbacks/assets/106274740/82dab032-c437-4e1b-8695-8e659ae9fb27)

**Smartphone (please complete the following information):**
 - Device: [Iphone 14]
 - OS: [Latest]
 - Browser [safari]
 - Version [Latest]

**Additional context**
Kindly check on learn to earn "Quest" submissions too ,i opened a ticket yesterday

**Comment by anouci** [comment]
Thanks for the feedback!

**Comment by NBMSacha** [comment]
Thanks a lot, just sorted it. Can you retry in 10 mins?

**Comment by BrianArunga** [comment]
Apparently the issue was also reported by @dao_duc_anh kindly check and confirm if so split the rewards if possible..Thank you
