### ISSUE TITLE
Mobula Earn page bug

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#39]
**Describe the bug**
Daily mission not functioning

**To Reproduce**
1. Go to mobula website
2. Click on mobula earn page
3. Scroll down to Daily missions
4. See  page loads but directs you back to another page

**Expected behavior**
When you tap on a daily mission it should load and open token details 

**Screenshots**
https://user-images.githubusercontent.com/106274740/222041285-8dc57c0d-d8fa-4df6-8066-a399941e0246.mp4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Samsung A73
 - Andriod 13
 - Browser Brave
 - Version 1.48.171

**Additional context**
When i connect my wallet it keeps on disconnecting

**Comment by Nando-Lorris** [comment]
Is this for the Edgecoin link?

**Comment by BrianArunga** [comment]
Yes both edgecoin and the other one
