### ISSUE TITLE
Portfolio displayed not correct

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#4]
**Describe the bug**
Portfolio section displays incorrect information about my assets.

**To Reproduce**
1. Go to 'mobula.fi'
2. Click on 'Portfolio'
3. See error

**Expected behavior**
Correct display of my assets.

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/211769808-789414c5-1563-45f6-86da-ec9f80c0cb0c.png)
![image](https://user-images.githubusercontent.com/122439863/211769962-e5a22b29-8cfd-4d7b-8618-ff02493c00e4.png)
For example Token Aidi Finance i have 5T but not 9.46T

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125

**Comment by NBMSacha** [comment]
Thanks very much! 

@ac57100 is currently working on that. Will be fixed within 2 hours.

**Comment by Midnight-yes** [comment]
Great!

**Comment by ac57100** [comment]
Hey there @Midnight-yes, thanks for the bug report! Do you remember by any chance if for the assets that were showing incorrect data, you had transactions that were doubled (same exact time/amount/type) on the "transaction" page?

**Comment by Midnight-yes** [comment]
> Hey there @Midnight-yes, thanks for the bug report! Do you remember by any chance if for the assets that were showing incorrect data, you had transactions that were doubled (same exact time/amount/type) on the "transaction" page?

Almost all my assets show a double amount. More precisely, a little less than double the amount. It seems to me that there is just a backlog somewhere. Previously, this was due to the fact that users re-added their wallet in the profile. This option is currently not available in the profile. A week ago, everything was displayed correctly for me, but after the update it became like this

**Comment by NBMSacha** [comment]
This should be fixed now. Can you please confirm @Midnight-yes ?

**Comment by Midnight-yes** [comment]
It's fixed!
