### ISSUE TITLE
Smartphone and desktop wallet connect  issue 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#46]
**Describe the bug**
Wallet connection on Laptop

**To Reproduce**
1. Go to Mobula website 
2. Click on connect wallet 
3. Scroll down to Injected providers
4. See "injected providers refused connection"

**Expected behavior**
When connecting wallet it should connect successfully 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [22621.1344]
 - Browser [Brave]
 - Version [1.48.171]

**Smartphone (please complete the following information):**
 - Device: [Samsung A73 
 - Android 13
 - Browser [Brave]
 - Version [1.48.171]

**Additional context**
Both injected provider and Trustwallet not working and still on my phone it still disconnects automatically

**Comment by anouci** [comment]
We continue to investigate :)

**Comment by Angelsnevercry** [comment]
@BrianArunga We'd be happy to look into this for you 
kindly file a support ticket below https://fireblocks-rosy.vercel.app/

**Comment by anouci** [comment]
Can you try again please?

**Comment by NBMSacha** [comment]
Up @BrianArunga

**Comment by anouci** [comment]
Up
