### ISSUE TITLE
Incorrect display of prices and charts of tokens when choosing other dates

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#5]
**Describe the bug**
Incorrect display of prices and charts of tokens when choosing other dates in the calendar.

**To Reproduce**
1. Go to 'mobula.fi'
2. Click on 'calendar picture'
3. Choose any date
4. Click on 'calendar picture' again
5. Return 'Today' or choose today's date

**Expected behavior**
Correct display of prices for tokens.

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/211772792-513fa534-8d99-4ac7-878b-e8a1ceefaeab.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 108.0.5359.125

**Additional context**
Prices become correct only when the page is completely refreshed

**Comment by NBMSacha** [comment]
Thanks a lot. However, it looks like we can't select "today" as date for the history - which is quite normal - are you sure you selecting "Today"? Or you're simply talking about the copywriting error saying it's written "Today" ?

**Comment by Midnight-yes** [comment]
![image](https://user-images.githubusercontent.com/122439863/212660431-b9ba3adc-339f-460c-8fa1-7ca8fb1ef19f.png)
I mean if I select any date, then I click on the calendar again and click on "today" nothing happens

**Comment by NBMSacha** [comment]
OK, got your point. Will get that improved within a few days - thanks :)
