### ISSUE TITLE
Incorrect vote history and listing time in DAO

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#50]
**Describe the bug**
In the voting history, the token is shown as already being voted many days ago, although in fact it is still in the voting stage. For example, at the moment, the KUSH ALIENZ token. This issue has been observed with other tokens as well.

**To Reproduce**
1. Go to '[Protocol DAO](https://mobula.fi/dao/protocol/overview)'
2. Scroll down to 'History'
4. See incorrect days and votes

**Expected behavior**
Correct display in history

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/224455397-66464886-e7c6-49aa-a731-5f5091e3d2e6.png)
![image](https://user-images.githubusercontent.com/122439863/224455426-b5eb4288-cacf-445b-9369-8fbd1b3218e5.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [110.0.5481.178]

**Comment by NBMSacha** [comment]
Hello, this is fixed!
