### ISSUE TITLE
Not all buttons work when trading

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#51]
**Describe the bug**
When you try to press the MAX button while trading, the value is set to 0, although can set the value manually.

**To Reproduce**
1. Go to '[Trade](https://mobula.fi/trade)'
2. Connect wallet in Etherium mainet network
3. Click on 'MAX button'
4. See error (The maximum value is not set)

**Expected behavior**
Either the system should give an error that 'Your balance is too small for the swap', or a value should be set. In my case, I had more than $10 in ETH on my balance

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/224611812-cb02b0de-b1be-4ae4-836d-0916e87e3bb8.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [110.0.5481.180]

**Comment by anouci** [comment]
This problem comes from the fact that the user does not have enough to pay the gas, the new version will improve the UX so that the user understands what is happening.
