### ISSUE TITLE
Failed to go to main page

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#61]
**Describe the bug**
When you go from any page of tokens to the main page, the url changes, but the page itself does not

**To Reproduce**
1. Go to '[Main page](https://mobula.fi/)'
2. Scroll down to 'Page numbers'
2. Click on 'any page'
3. Click on 'Main page'

**Expected behavior**
Correct page display

**Screenshots**
So I went to page 5 for example
![image](https://user-images.githubusercontent.com/122439863/226777369-f74c4ce8-f2f5-4a57-8ea0-1dc4213a6c32.png)

Now I click on the main page (the inscription at the top left). There is a redirect to the main page, but tokens from the 5th page are still displayed
![image](https://user-images.githubusercontent.com/122439863/226777464-49135793-e3b6-41e3-8e18-2e34a9b0765e.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [111.0.5563.110]

**Comment by Midnight-yes** [comment]
> Thanks Akop! We will fix it immediately

Ok. I will check again later. Not fixed yet

**Comment by NBMSacha** [comment]
This will probably stay for a few, will add it to our backlog and close it as it's not a "real" issue, but an UX improvement.
