### ISSUE TITLE
big displayed LOGO and move chart high price movements

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#62]
![Screenshot_20230322-205143_Brave](https://user-images.githubusercontent.com/122985679/226927147-5f4c299d-db80-49b7-b19f-77fed8c9fa3b.jpg)
![Screenshot_20230322-205057_Brave](https://user-images.githubusercontent.com/122985679/226927173-eb404b31-22cd-4d48-a895-5c346628ca9d.jpg)

**Comment by anouci** [comment]
Thank you! Fixed

**Comment by anouci** [comment]
Not yet
