### ISSUE TITLE
Arbitrum contract addresses

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#65]
**Describe the bug**
Contract addresses of ARB are not in the right sequence on  3 networks ...When you click on ARB smartchain it gives you ARB ERC20 and when you click on ARB ERC20 it give you ARB of it's own network and when you tap on ARB,ARB network it tells you not found

**To Reproduce**
1. Go to Real time price chart
2. Click on Arbitrum token
3. Scroll down to Links
4. Contract addresses 

**Expected behavior**
Addresses should be in the right sequence 

**Screenshots**
https://user-images.githubusercontent.com/106274740/227712552-51ffac61-96da-424d-a638-bf3bef9f5af4.mp4

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: A73
 - Android 13

**Additional context**
I reported a bug on Mobula dex comparator ...when i want to buy tokens or coins worth $1000 the comparator goes blank only functions with a figure less $1000

**Comment by anouci** [comment]
Thank you Brian, we will check that

**Comment by NBMSacha** [comment]
This has been sorted.
