### ISSUE TITLE
No accrual for the last DAO voting

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#66]
**Describe the bug**
After the end of the final voting for the token ShibWallet, 66.6 MOBLs have not been received. And also the voice was not recorded, as it was 355 votes and remains

**To Reproduce**
1. Go to '[DAO](https://mobula.fi/dao/protocol/overview)'
2. See error

**Expected behavior**
Correct rewards for voting

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/227768955-dc92889a-3688-4d33-9c23-4b0c31988886.png)
![image](https://user-images.githubusercontent.com/122439863/227769076-11f4c0a4-dfaf-4cec-b959-5a1c3b51daec.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [111.0.5563.111]

**Comment by anouci** [comment]
Hey :) This bug has already been reported. Thank you
