### ISSUE TITLE
Token listed but not displayed

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#67]
**Describe the bug**
Token Arbitrum listed on Mobula 4 days ago but still not displayed

**To Reproduce**
1. Go to '[Token page](https://mobula.fi/asset/arbitrum)'
2. See error

**Expected behavior**
If information appears that the token is listed, then the information should arrive correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/228008245-73a7ecaf-d7c0-4e98-af48-2be08fb80a11.png)
![image](https://user-images.githubusercontent.com/122439863/228008359-747c0e58-47ee-456f-a986-34c4d4a5ae0a.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [111.0.5563.111]

**Comment by anouci** [comment]
It takes some time before the data is added to the db

**Comment by Midnight-yes** [comment]
> It takes some time before the data is added to the db

Yes, but other tokens that were listed a few days later have already appeared, but this one does not

**Comment by NBMSacha** [comment]
It's simply because Arbitrum chain isn't supported yet :)
