### ISSUE TITLE
No accrual for the last DAO voting

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#68]
**Describe the bug**
After the end of the final voting for the token Amazon AI  (ID: 29), 66.6 MOBLs have not been received. I'm create issue on Github #66  but [anouci](https://github.com/anouci) closed it with a note that they had already reported such a problem but I do not see that there is an open ticket with such a problem. In total, I have already lost 133.2 MOBL

**To Reproduce**
1. Go to '[DAO](https://mobula.fi/dao/protocol/overview)'
2. See error

**Expected behavior**
Correct rewards for voting

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/228195737-89267163-31ca-4989-89fe-60e25bcaa5dc.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version 111.0.5563.112 ]
 
I'll just create an issue so that they don't forget to send airprop through the air

**Comment by Midnight-yes** [comment]
The same problem with new token

**Comment by NBMSacha** [comment]
Thanks for this, starting to dig into it this week-end.

**Comment by NBMSacha** [comment]
Thanks! Solved.
