### ISSUE TITLE
Error in trade tab

### ISSUE THREAD

**Issue by Attractor1one** [MobulaFi/mobula-feedbacks#69]
**Describe the bug**
If you change the network several times in the "Trade" tab, an error appears ->Application error: a client-side exception has occurred (see the browser console for more information).

**To Reproduce**
1. Go to 'https://mobula.fi/trade'
2. Click on 'Chain' in Meta-DEX Aggregator
3. Change network several times

**Expected behavior**
No errors when changing network in DEX.

**Screenshots**
![2023-03-28_1](https://user-images.githubusercontent.com/126772418/228198309-f5e7d11d-f19c-4152-935e-60532ce2671b.png)
![2023-03-28_2](https://user-images.githubusercontent.com/126772418/228198324-ab7b0ba8-8123-48ac-9a22-3e2de7e49e4f.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [111.0.1]

**Comment by NBMSacha** [comment]
Hey! Thanks a lot for this.

Few questions: 
- How many times do we need to change network? 
- When you mean "change network", are you clicking on the new chain and closing the popup, or really switching on your wallet? 

Thanks!

**Comment by Attractor1one** [comment]
Hi! 
4 times or more.
Yes, I changed in MM the Polygon network to Ethereum and back

**Comment by NBMSacha** [comment]
Hey! Just pushed an update. Can you please let me know if that's still around? by the way, failed to reproduce the error, just done that based on the error logs you shared.

**Comment by NBMSacha** [comment]
Up @Attractor1one

**Comment by Attractor1one** [comment]
Hi sir @NBMSacha!
I checked again,  + added other networks in MM: Harmony, Moonriver, Aurora, Cronos
I don't see the error anymore!
