### ISSUE TITLE
Mobula Meta-aggregator

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#70]
**Describe the bug**
On meta-Aggregator when i switch network it shows me "error" signal

**To Reproduce**
1. Go to Tools
2. Click on Trade
3. Scroll down to Meta-Dex Aggregator 
4. Switch chain i.e Eth to Smartchain =Error something went wrong

**Expected behavior**
It should be able to switch once a request is placed

**Screenshots**
![IMG-20230328-WA0000.jpg](https://user-images.githubusercontent.com/106274740/228259521-22f13d51-1812-4117-90dd-40114c572b31.jpg)

.

**Desktop (please complete the following information):**
 - Windows 
- Brave browser
 - Version (1.49.128)

**Smartphone (please complete the following information):**
 - Device: Samsung A73 
 - Android 13
 - Browser [Brave]
 - Version [1.49.122]

**Additional context**
System take quite some time to load unlike before

**Comment by Midnight-yes** [comment]
> Hey Brian can you share a video, please? I can't reproduce the bug

There was such an error too, but after refreshing the page it disappeared and switching between networks began to work correctly

**Comment by BrianArunga** [comment]
Am now using the app I'll give you findings in afew
