### ISSUE TITLE
PROTOCOL DAO VOTING

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#71]
A few months ago, before the system upgrade, the PROTOCOL DAO members used to wait for atleast 30 minutes before voting on new listings. This gave the DAO enough time to read thoroughly on the listings, then vote accordingly. But 30 minutes was a very long time to wait. 

The 30 minutes was scrapped of to zero, meaning any project that gets listed immediately gets to be voted in fast because the DAO has grown significantly, and members are always ready to vote. 

The issue comes in when a project get listed and immediately votes start to come in, less than 5mins after the listing which leads to posing this question, how much time do we really need in order to verify the details of the listings then vote? How much education does the DAO have on voting for new projects? 

We are the game changer, and it would be best 
1. To bring back the time that was there in the beginning, but not 30 minutes of course. It can be different for the normal listing and fast listing.
2. Educate the PROTOCOL DAO on the importance of voting wisely after scrutinising the projects. 

Long live Mobula!

**Comment by NBMSacha** [comment]
Added back limit. Thanks for this, great idea.
