### ISSUE TITLE
Approve error

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#72]
**Describe the bug**
When trying to approve a token for a swap, the system gives an error

**To Reproduce**
1. Go to '[Trade](https://mobula.fi/trade)'
2. Changed the network to ETH
3. I entered the address of the contract of the token that I want to sell (in the example, the MAGE token is indicated)
4. Click on Pre-approve button
5. See error

**Expected behavior**
Correct work of the trade

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/228404680-da4292d9-545f-46bc-aa71-863edd7ff8f3.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [111.0.5563.147]

**Comment by NBMSacha** [comment]
Hey! Can you please retry and share the console logs (inspector) ? thanks!

**Comment by anouci** [comment]
Up! :)

**Comment by NBMSacha** [comment]
Any news? @Midnight-yes

**Comment by Midnight-yes** [comment]
> Any news? @Midnight-yes

It's okay now for that token! Great
