### ISSUE TITLE
The token disappeared on the main page

### ISSUE THREAD

**Issue by Attractor1one** [MobulaFi/mobula-feedbacks#74]
**Describe the bug**
No KuCoin token in the "Top 100" list on the main page.

**To Reproduce**
1. Go to 'https://mobula.fi/asset/kucoin'
2. See rank
3. Go to 'https://mobula.fi/'
4. Not in the list of tokens

**Expected behavior**
Add KuCoin token in the "Top 100" list on the main page.

**Screenshots**
![2023-03-30_1](https://user-images.githubusercontent.com/126772418/228810977-6f88c38e-873f-4da1-a73f-741a06a8008c.png)
![2023-03-30_2](https://user-images.githubusercontent.com/126772418/228810984-14c7f934-153e-4fa3-a537-0feee1bd92e5.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [111.0.1]

**Comment by anouci** [comment]
Thank you!

**Comment by NBMSacha** [comment]
hello! This isn't an issue - the asset's criterium for being displayed on top100 (here volume) is just too low.
