### ISSUE TITLE
Social Metrics in asset Mobula does not work

### ISSUE THREAD

**Issue by Attractor1one** [MobulaFi/mobula-feedbacks#75]
**Describe the bug**
Twitter subscriber counter on Mobula asset stopped counting.

**To Reproduce**
1. Go to 'https://mobula.fi/asset/mobula'
2. See "Social Metrics" -> Twitter
3. Check the quantity 'https://twitter.com/MobulaFi'

**Expected behavior**
Fix the meter Twitter subscriber counter on Mobula asset.

**Screenshots**
![2023-03-30_3](https://user-images.githubusercontent.com/126772418/228816200-42d83fb3-d19c-441d-97d3-4834dde441fe.png)
![2023-03-30_4](https://user-images.githubusercontent.com/126772418/228816215-3e4085ad-006a-4bd3-9225-b93e20d27dbd.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [111.0.1]

**Comment by anouci** [comment]
Thank you! The problem comes from the Twitter API

**Comment by NBMSacha** [comment]
Thanks! This will be sorted within the week.
