### ISSUE TITLE
PROTOCOL DAO REWARDS

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#77]
Rewards have not been received for voting (Final Validation). Hash provided for reference. 

1. Ticket3 (listed 13 hours ago) 
0x3f7cc411ed8f0f6aecaae67435c76b911a1ff805a4810fc2251ed53cda8d7d6b

2. Kuka (listed 2 days ago).  
0x60c42ce4acefba899c8c675b49eb87da98001a02a2bd43d69cf5e243649e9e5f

Regards,
Muhonja.

**Comment by NBMSacha** [comment]
Hey! Duplicate of issue #68 - solved. Thanks!
