### ISSUE TITLE
PROTOCOL DAO VOTING

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#78]
Countdown timer was implemented on voting for new listings but the timer reads 0:00. This will make it hard for Rank 1 members to know when the timer really ends and when to start voting. 
Kindly check on it. 

![Screenshot_20230331_114928_Trust Wallet.jpg](https://user-images.githubusercontent.com/101212685/229087878-e4f86b9e-b3f9-4446-818d-2f38b4b2fdb3.jpg)

Regards, 
Muhonja.

**Comment by anouci** [comment]
Already reported :) Thanks
