### ISSUE TITLE
Another bug with countdown in governance staking

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#81]
**Describe the bug**
30 days have passed since the tokens were staked, the timer has reached 0 and shows 30 days again.

**To Reproduce**
1. Go to '[Governance](https://mobula.fi/dao/governance/staking)'
2. See wrong staking time

**Expected behavior**
It is necessary that the remaining staking time is displayed correctly. I sent for 100 days, a month has passed, so 70 days should be displayed

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/229265401-9c000911-413d-4a55-8d51-61028a45769a.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [111.0.5563.147]

**Comment by NBMSacha** [comment]
Actually, you staked 2023-02-25 02:15:01 till June (https://polygonscan.com/tx/0x6503b1a4fa3729b620045763ba05f89e7506b43fa29d2d1786599de1222cf83f) and last month you just upgraded the amount staked, but not the time. So that's why.
