### ISSUE TITLE
speed slows down when sorting networks in the recently added and trending page sections

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#84]
when opening page gainers and losers the loading speed is normal, but when after opening the recent add or trending page everything becomes slow and like lagging like the one in the video..

https://user-images.githubusercontent.com/122985679/229304250-b3602fac-e77f-4c54-9376-f9580c2b00d5.mp4

**Comment by anouci** [comment]
Thanks! The team is working on improving the speed
