### ISSUE TITLE
NFT does not show everything in the portfolio

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#86]
when checking the NFT in the mobula user profile, it works and shows all the NFTs...
https://user-images.githubusercontent.com/122985679/229870961-f5f7c32e-52e7-4b67-8a93-7b9f4af83ab7.mp4
But when opening the portfolio it's still not there at all. only part of it is shown.

https://user-images.githubusercontent.com/122985679/229871874-33bde45e-35c6-4f35-b2ff-672e25b2f63d.mp4

**Comment by NBMSacha** [comment]
Thanks a lot! Will be fixed this week.
