### ISSUE TITLE
Protocol Dao on Desktop 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#87]
**Describe the bug**
I'm having an issue once i log into the mobula app or website and try to access protocol Dao First sort and final validation remains blank even though we have a token that has been submitted for voting.

**To Reproduce**
1. Go to Protocol Dao 
2. Click on First sort or final validation 
3. Scroll down to the submitted token to be voted on
4. See error "Doesn't appear

**Expected behavior**
Tokens submitted for voting should appear just like how they appearing on mobile phones

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Browser [Chrome]

**Comment by anouci** [comment]
Ok thank you :) Can you share a screenshot please

**Comment by anouci** [comment]
Up :)
