### ISSUE TITLE
Protocol Dao 

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#88]
**Describe the bug**
I did vote today on the token that was was submitted earlier today ,transaction were executed but bot hasn't updated anything yet 

**To Reproduce**
1. Go to Mobula dao
2. Click on protocol dao
3. Scroll down to First sort 

**Expected behavior**
Once a vote has been validated successfully and transaction executed successfully it should appear on both discord and Tg for one to get their rewards

Transaction hash**

0xf3b404d45c4ef8da9fa35a52fabb9d5da731ea01b0d6283749983801be6ed62b
0x759b9e17611941887341c0649dd4ea21b9cb21ec3cf79176d2914a2a6d1c8da9

**Smartphone (please complete the following information):**
 - Device: Samsung A73 
 - Android 13

**Comment by anouci** [comment]
Can you verify again please

**Comment by anouci** [comment]
Up
