### ISSUE TITLE
Comment section not working 

### ISSUE THREAD

**Issue by victorgwatana** [MobulaFi/mobula-feedbacks#89]
**Describe the bug**
A clear and concise description of what the bug is. The comment section on coins is not working, when trying to make a comment on a listed coin like BTC when I click on submit, nothing happens.

**To Reproduce**
1. Go to home page
2. Click on click on BTC
3. Scroll down to comment section 

**Expected behavior**
When a comment is submitted, it should appear on the list of comments made by users.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: android 
 - Browser 
![Screenshot_20230405-143222](https://user-images.githubusercontent.com/72771715/230101113-09743569-ee4c-4e67-9566-bfbdb8423dcc.jpg)
Chrome 

**Additional context**

**Comment by anouci** [comment]
Thank you :)
