### ISSUE TITLE
Token BKR pulselorian vol 24h is not on the Recently add page.

### ISSUE THREAD

**Issue by rian64** [MobulaFi/mobula-feedbacks#91]
token on page recently added vol 24h. 0.00%. but if you click on the specific token, it's all there. 

https://user-images.githubusercontent.com/122985679/230276042-65c0c8b8-e401-43d5-8644-24e2ac1d8428.mp4

**Comment by anouci** [comment]
Thank you :)

**Comment by anouci** [comment]
Actually, this is not a bug. As long as you don't have 1 trade on the assets, we don't compute the prices

**Comment by rian64** [comment]
what does that mean I have to have trading assets in the token first then the vol is there?
