### ISSUE TITLE
Protocol DAO Voting 

### ISSUE THREAD

**Issue by realMuhonja** [MobulaFi/mobula-feedbacks#92]
A proposal has been raised by @Victorgwatana (TG username) on Governance DAO on giving Rank 1 members ample time to vote before Rank 2 members can join in to assist. 
My proposal is to implement that, then consider the following: 

1. Add a considerable amount of time so as not to inconvenience projects that have paid for fast listing. 
When the time elapses, then Rank 2 members can finish up on the pending spots on First Sort so that the listing can move to Final Validation. 

2. Mobula sending notifications to all Protocol DAO members for new listings and how much time Rank 1 members have to vote before Rank 2 members can take over. This will require asking for phone numbers from Rank 1 and 2 members. 
It should not be mandatory for all members to send their numbers, but only if they are willing. 
The aim is to ease the time wasted on waiting for listings to be voted on. 

Regards, 
Muhonja.

**Comment by anouci** [comment]
Thank you please open a Discussion :)
