### ISSUE TITLE
Error when claiming for DAO voting

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#94]
**Describe the bug**
When trying to claim MOBL for DAO voting, the system gives an error

**To Reproduce**
1. Go to '[Protocol DAO](https://mobula.fi/dao/protocol/overview)'
2. Click on 'Claim'
3. See error

**Expected behavior**
Correct Claim

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/230511379-9d5c9268-9cbc-4fed-a816-c75f609ea0f8.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [111.0.5563.147]

**Comment by anouci** [comment]
Did you try to refresh the page?

**Comment by Midnight-yes** [comment]
> Did you try to refresh the page?

Of course. And i try from different devices. The same error

**Comment by anouci** [comment]
Is the problem still there?

**Comment by Midnight-yes** [comment]
> Is the problem still there?

Nope. It solved!
