### ISSUE TITLE
Top 100 list error

### ISSUE THREAD

**Issue by Nando-Lorris** [MobulaFi/mobula-feedbacks#95]
**Describe the bug**
Tron (TRX) is listed as #16 but does not show up on the list

**To Reproduce**
1. Go to mobula.fi
2. Click on top 100
3. Scroll down to p16

**Expected behavior**
Should be around number 16 but doesn't show at all

**Screenshots**
![Screenshot_20230408-102328_Trust Wallet](https://user-images.githubusercontent.com/126595330/230729737-e3089aa0-fd6e-4efe-b2d8-8d59d8e52825.jpg)

**Smartphone (please complete the following information):**
 - Device: Android 
 - Browser Trust Wallet 

**Additional context**

**Comment by anouci** [comment]
Thank you for the report
