### ISSUE TITLE
Hidden tokens in the portfolio cannot be displayed again

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#96]
**Describe the bug**
If you hide the token, then after a while it cannot be displayed again. Button "Restore Hidden Tokens" don't work. But in the section "My assets" all tokens are displayed

**To Reproduce**
1. Go to '[Portfolio](https://mobula.fi/portfolio)'
2. Click on 'Hide Asset '
3. After a while, try to restore

**Expected behavior**
Correct recovery of hidden assets

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/230811140-16395902-8fcd-42db-b96f-9a7a55eb2da9.png)
![image](https://user-images.githubusercontent.com/122439863/230811692-a72a5da8-e854-4b3e-a200-c75d539dd366.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [111.0.5563.148]
 - 
**Additional context**
As you can see from the screenshots, only 3 tokens are displayed in the portfolio and it is impossible to return the rest, which I hid earlier. However, in the "my assets" section, you can see that I have other tokens on my wallet

**Comment by anouci** [comment]
Sorry but I can't reproduce this bug. Please let me know if the problem persists

**Comment by Midnight-yes** [comment]
> Sorry but I can't reproduce this bug. Please let me know if the problem persists

How can i attach video here?

**Comment by Midnight-yes** [comment]
https://user-images.githubusercontent.com/122439863/230880203-6b41d6bc-6690-4a11-a5c8-33bc19d22778.mp4

**Comment by anouci** [comment]
Ok thanks

**Comment by Midnight-yes** [comment]
Solved!
