### ISSUE TITLE
Share watchlist button not working

### ISSUE THREAD

**Issue by Midnight-yes** [MobulaFi/mobula-feedbacks#97]
**Describe the bug**
Can't click share watchlist button

**To Reproduce**
1. Go to '[Watchlist](https://mobula.fi/watchlist)'
2. Click on 'Share'
3. See error

**Expected behavior**
Correct button press

**Screenshots**
![image](https://user-images.githubusercontent.com/122439863/231620061-eee3c745-3d48-47ce-8482-eeb0b07a3cbb.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [112.0.5615.87]

**Comment by anouci** [comment]
Thank you for the feedback. Currently, sharing your watchlist is not available
