### ISSUE TITLE
Smart contract call error

### ISSUE THREAD

**Issue by BrianArunga** [MobulaFi/mobula-feedbacks#99]
**Describe the bug**
Protocol dao claim section when you tap to claim you get a smart contract error

**To Reproduce**
1. Go to Mobula dao
2. Click on protocol dao
3. Scroll down to claim button 
4. See "Smart contract call error"

**Expected behavior**
When claiming smart contract call should be in a position to allow you approve the process

**Screenshots**
![Screenshot_20230415_043220_Trust Wallet.jpg](https://user-images.githubusercontent.com/106274740/232177033-51a9a1d2-2e7f-4595-964c-4edae7b4cfaa.jpg)
![Screenshot_20230415_044143_Trust Wallet.jpg](https://user-images.githubusercontent.com/106274740/232177147-c2e477c8-12e6-4aa6-ae08-3507ebd1003e.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Android
 - OS: 13

**Comment by anouci** [comment]
Hey! The bug is still here?
